### ISSUE TITLE
CV vs mean looks weird

### ISSUE THREAD

**Issue by slinnarsson** [velocyto-team/velocyto.py#104]
I'm getting weird results from CV vs mean fitting (`vlm.score_cv_vs_mean()`). To reproduce the error, I first installed a fresh Anaconda:

```bash
bash Anaconda3-5.2.0-MacOSX-x86_64.sh 
```

Then I installed velocyto and its dependencies:

```bash
conda install -c r -c bioconda pysam
conda install numpy scipy cython numba matplotlib scikit-learn h5py click
pip install velocyto
```

I got a warning that "distributed 1.21.8 requires msgpack, which is not installed" so I did `pip install msgpack`to be sure. 

I then checked out the dentate gyrus notebook by doing `git checkout -- python/DentateGyrus.ipynb` and executed it one step at a time (including downloading the data from Kharchenko's server). After step 10, the expected result is

![unknown](https://user-images.githubusercontent.com/10656387/44830872-d6cf5e00-abd8-11e8-92b3-c08f59c4c54c.png)

but I got instead

![dentatecvmean](https://user-images.githubusercontent.com/10656387/44830880-e0f15c80-abd8-11e8-84bb-aa7f134ffd9b.png)

There's nothing apparently wrong with the data, because if I compute CV and mean manually I get:

![dentatecvmean_data](https://user-images.githubusercontent.com/10656387/44830898-01211b80-abd9-11e8-8ed8-ad96f4afdf2f.png)

Also tried using velocyto 0.17.8 but got the same weird result.

If I continue executing the dentate notebook, step 13 (PCA) goes to 100% on all cores and never seems to end (it used to be quick). 

I've run this notebook many times in the past with no issues. I also now tried the Haber notebook, and the CV-mean plot also looks weird. I have no idea what could be wrong, and would appreciate any suggestions.

**Comment by gioelelm** [comment]
I have seen this error in a previous issue (#87) here on github... It was a
Mac specific problem, I remember that I was also puzzled by it, I reviewed
the code again now and I am still puzzled. Have you tried to extract the
class method from source and debug it on the notebook? You can define it as
a function and call it on the vlm object.

**Comment by slinnarsson** [comment]
Ok, so it has something to do with how the layer data is loaded or scanned. This gives the weird plot:

```python
with loompy.connect("data/DentateGyrus.loom") as ds:
    s = ds["spliced"][:,:]
mu = np.mean(s, 1)
cv = np.std(s, 1)/mu
plt.scatter(x=np.log2(mu), y=np.log2(cv),lw=0,marker='.')
```

But this gives the correct plot:

```python
with loompy.connect("data/DentateGyrus.loom") as ds:
    (mu, std) = ds["spliced"].map((np.mean, np.std), axis=0)
    cv = std / mu
plt.scatter(x=np.log2(mu), y=np.log2(cv),lw=0,marker='.')
```

I narrowed it down to this clean case (`s` is the `uint16` matrix "spliced" loaded in memory):

```python
>>> np.mean(s,axis=1)[0], np.mean(s[0,:])
(0.0266842365343436, 0.0266842365343436)

>>> np.std(s2,axis=1)[0], np.std(s2[0,:])
(46.214421157714305, 0.17203480247697106)
```

So calculating `np.std` gives different results if you do it on a whole matrix along an axis, then take the first result, vs you take the first row and apply `np.std` to it.... (`np.mean` behaves normally). Converting to `float32` does not help.

Actually, it can be narrowed down to something that depends solely on `numpy`:

```python
>>> x = np.arange(1000000).reshape(1000,1000)
>>> np.std(x,axis=1)[0], np.std(x[0,:])
(9.473833110724544e+20, 288.6749902572095)
```
It might be related in spirit to the bug I found in `np.sqrt` caused by some MKL optimisation added by Anaconda (https://github.com/ContinuumIO/anaconda-issues/issues/9129 and https://github.com/numpy/numpy/issues/11448), except in that case at least the results were correct.

However, running the code snippet above in the terminal, or in a new notebook, gives the correct result. Confusing. I will sleep on this now. 

*Update:* If I run the pure numpy example before I run velocyto, the results are correct *and velocyto gives the correct CV-mean plot*. If I run velocyto first, the CV-mean plot is wrong and running the numpy example afterwards gives the wrong results. So something about the code in that notebook jinxes np.std.

**Comment by gioelelm** [comment]
There is some compiled cython and some numba functions... After which
function call numpy std breaks?

**Comment by pberkes** [comment]
I can confirm this problem, and have made some progress in debugging it:

- The problem can be traced down to a single line inside of `numpy`: in `numpy\core\_methods.py`, in the function `_var`, there is a matrix multiplication performed as `x = um.multiply(x, x, out=x)`. Notice that the output of the multiplication is saved on the same array as the input.

- When the `velocyto.speedboosted` extension module is loaded, this triggers the parallel computing features in MKL, and so using the `x` array as output is not safe any more.

- To support this:

0) This line reproduces the problem (I deleted `velocyto.__init__` so that here we import `speedboosted` alone):
```
$ python -c 'import numpy as np; import velocyto.speedboosted; x = np.arange(1000000).reshape(1000,1000); print(np.std(x,axis=1)[0], np.std(x[0,:]))'`
9.473833110724544e+20 288.6749902572095
```

1) If I change the line `x = um.multiply(x, x, out=x)` to `x = um.multiply(x, x)`, the problem disappears
```
$ python -c 'import numpy as np; import velocyto.speedboosted; x = np.arange(1000000).reshape(1000,1000); print(np.std(x,axis=1)[0], np.std(x[0,:]))'`
288.6749902572095 288.6749902572095
```

2) If I manually set the number of MKL threads to 1, the problem disappears. The result also depends on the number of threads:
```
$ export MKL_NUM_THREADS=1; python -c 'import numpy as np; import velocyto.speedboosted; x = 288.6749902572095 288.6749902572095
```

```
$ export MKL_NUM_THREADS=2; python -c 'import numpy as np; import velocyto.speedboosted; x = np.arange(1000000).reshape(1000,1000); print(np.std(x,axis=1)[0], np.std(x[0,:]))'
111803.21253596651 288.6749902572095
```

```
$ export MKL_NUM_THREADS=8; python -c 'import numpy as np; import velocyto.speedboosted; x = np.arange(1000000).reshape(1000,1000); print(np.std(x,axis=1)[0], np.std(x[0,:]))'
9.473833110724544e+20 288.6749902572095
```

It is unclear to me at the moment if this is a bug in `numpy`, in the `MKL` library shipped with Anaconda, or somewhere else. I'll try to create a minimal example independence of `velocyto` and open a ticket on the `numpy` repository, to see if this is a known issue.

**Comment by slinnarsson** [comment]
Great, thanks for helping chase this down! Since it depends on MKL (and multithreading), it seems more likely to be a bug specific to anaconda numpy, or possibly cython. Ordinary numpy does not use MKL afaik, and thus `x = um.multiply(x, x, out=x)` should be an essentially atomic operation. MKL should be free to multithread it, but ought to take care not to change the semantics of numpy.

Clearly this is a very bad bug, which might surely have already screwed up people's computations without them even noticing.

**Comment by pberkes** [comment]
I opened a ticket with Anaconda, and apparently this is related to a known issue. Updating `numpy` solves the problem. See https://github.com/ContinuumIO/anaconda-issues/issues/10089

On the other hand, it would be only natural for users of `velocyto` to install the latest Anaconda, run their analyses, and get wrong results...

**Comment by slinnarsson** [comment]
Closing as we have a reasonable check in place, and hoping Anaconda will fix the issue soonish.
