### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by shaaaarpy** [velocyto-team/velocyto.py#105]
Always shows syntax error for python3

![image](https://user-images.githubusercontent.com/23281566/44950351-43f62400-ae63-11e8-9116-c2e15637d182.png)

**Comment by sharpy013** [comment]
I install it with python3.6 and it installed perfectly.
But after running velocyto command i get
ModuleNotFoundError: No module named '_tkinter' error, Updating python3-tk
does not help.

**Comment by gioelelm** [comment]
Are you using a new conda environment? Do you have tkinter installed?

**Comment by gioelelm** [comment]
Velocyto does not use tkinter. Maybe the bug is somehow related to
matplotlib backend. Or somehow installing python3.6 on your previous
environment has corrupted something. Have you tried with a fresh conda
environment?

**Comment by sharpy013** [comment]
This is the error i am getting. I have updated matplotlib and tkinter both
Thank you

**Comment by gioelelm** [comment]
Sorry, I am not sure I understand. Your last message is maybe incomplete.
Do you mean the problem is solved?

**Comment by sharpy013** [comment]
No i am still getting the same error.

This is the error

**Comment by gioelelm** [comment]
You are failing to attach the error.

**Comment by gioelelm** [comment]
Copy paste the full traceback

**Comment by sharpy013** [comment]
This is the full traceback i have pasted

**Comment by gioelelm** [comment]
Then please use conda as we specify in the instructions.

We are glad to help everybody to get velocyto up and running. However, for
us is impossible to solve every problem reported without staring from a
common ground: many kinds of weird installation and runtime problems might
occur in different systems and environments. Conda instead provides a
sandboxed and stereotypical installation of python and dependencies and we
feel that we can effectively offer support to users if they use it.

As a testimony of this, we managed to solve every installation problem
reported by users, as long as they used conda.

**Comment by sharpy013** [comment]
I have set up the conda environment given in the installation guide but
still i am getting the same error.
thank you

**Comment by gioelelm** [comment]
I need more info. For example which operative system are you using? Can you
import tkinter in a shell?

Is tk set as you matplotlib backend in the matplotlib configuration file?
If yes change it to something else.
