### ISSUE TITLE
run error - valid_bcs2idx referenced before assignment

### ISSUE THREAD

**Issue by joshua-gould** [velocyto-team/velocyto.py#11]
Command: velocyto run -o vel-run-test -m mm10_rmsk_joined.gtf test.bam mm10-1.2.0_gene_ivls.txt
  
File "/miniconda/lib/python3.6/site-packages/velocyto/commands/run.py", line 87, in run
    additional_ca)
  File "/miniconda/lib/python3.6/site-packages/velocyto/commands/_run.py", line 84, in _run
    exincounter = vcy.ExInCounter(valid_bcs2idx)
UnboundLocalError: local variable 'valid_bcs2idx' referenced before assignment

**Comment by joshua-gould** [comment]
Error resolved when specifying barcodes

**Comment by gioelelm** [comment]
Still it should work without specifying barcode.

Personal Note: I will have to fix it, maybe it makes sense to delay dealing with this to the changes bringing full support of the DropSeq pipeline.
