### ISSUE TITLE
GTF error with no reasons ! IndexError: list index out of range

### ISSUE THREAD

**Issue by Suger0917** [velocyto-team/velocyto.py#117]
Dear Velocyto Team,

when running( code:  velocyto run -b barcode.tsv -o ./ ./out.bam $genome_annotation_test.gtf ),  if the input file $genome_annotation_test.gtf with these lines, as shown below. I got errors, which is also shown below. Dear, I have tried sooo many times and so long time to fight with this Bug, but does't work!!!!
Please, please help me !
Anyone knows why??? Thanks sooooo much!!

![image](https://user-images.githubusercontent.com/22163018/45827404-f6b1f780-bd28-11e8-9bfe-882512d4df48.png)
chr1    stdin   exon    33473541        33476434        .       -       .       gene_id "AK2"; transcript_id "NR_037591"; exon_number "1"; exon_id "NR_037591.1"; gene_name "AK2";
chr1    stdin   exon    33473541        33476434        .       -       .       gene_id "AK2"; transcript_id "NM_013411"; exon_number "1"; exon_id "NM_013411.1"; gene_name "AK2";
chr1    stdin   exon    33473541        33476434        .       -       .       gene_id "AK2"; transcript_id "NM_001199199"; exon_number "1"; exon_id "NM_001199199.1"; gene_name "AK2";
chr1    stdin   exon    33476826        33479003        .       -       .       gene_id "AK2"; transcript_id "NR_037592"; exon_number "1"; exon_id "NR_037592.1"; gene_name "AK2";
chr1    stdin   exon    33476826        33479003        .       -       .       gene_id "AK2"; transcript_id "NM_001625"; exon_number "1"; exon_id "NM_001625.1"; gene_name "AK2";
chr1    stdin   exon    33478808        33479003        .       -       .       gene_id "AK2"; transcript_id "NR_037591"; exon_number "2"; exon_id "NR_037591.2"; gene_name "AK2";
chr1    stdin   exon    33478808        33479003        .       -       .       gene_id "AK2"; transcript_id "NM_013411"; exon_number "2"; exon_id "NM_013411.2"; gene_name "AK2";
chr1    stdin   exon    33478808        33479003        .       -       .       gene_id "AK2"; transcript_id "NM_001199199"; exon_number "2"; exon_id "NM_001199199.2"; gene_name "AK2";
chr1    stdin   exon    33480123        33480195        .       -       .       gene_id "AK2"; transcript_id "NM_013411"; exon_number "3"; exon_id "NM_013411.3"; gene_name "AK2";
chr1    stdin   exon    33480123        33480195        .       -       .       gene_id "AK2"; transcript_id "NR_037591"; exon_number "3"; exon_id "NR_037591.3"; gene_name "AK2";
chr1    stdin   exon    33480123        33480195        .       -       .       gene_id "AK2"; transcript_id "NM_001625"; exon_number "2"; exon_id "NM_001625.2"; gene_name "AK2";
chr1    stdin   exon    33480123        33480195        .       -       .       gene_id "AK2"; transcript_id "NM_001199199"; exon_number "3"; exon_id "NM_001199199.3"; gene_name "AK2";
chr1    stdin   exon    33480123        33480195        .       -       .       gene_id "AK2"; transcript_id "NR_037592"; exon_number "2"; exon_id "NR_037592.2"; gene_name "AK2";
chr1    stdin   exon    33486968        33487062        .       -       .       gene_id "AK2"; transcript_id "NM_001625"; exon_number "3"; exon_id "NM_001625.3"; gene_name "AK2";

#### Error 
Traceback (most recent call last):
  File "/data1/zhangshu/software/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 212, in _run
    exincounter.mark_up_introns(bamfile=bamfile, multimap=multimap)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 694, in mark_up_introns
    ii.mark_overlapping_ivls(r)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/indexes.py", line 167, in mark_overlapping_ivls
    downstream_exon = feature.get_downstream_exon()
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/feature.py", line 59, in get_downstream_exon
    return self.transcript_model.list_features[ix]
IndexError: list index out of range

**Comment by Suger0917** [comment]
Hi, gioelelm. I followed your instruction and deleted the "exon_number" field. It worked perfectly!!!
Thank you so much!

> Have you tried with different gtf files? For example with the ones downloaded from gencode?
> 
> I am not sure 100%, but I have a feeling that this is a notation issue...
> If I remember correctly, the numbering of exons on strand minus "-" in gencode is the other way around.
> For example for a gene with 10 exons the exon on the strand - at the 5' most of the reference sequence (that is always given on the + strand) should be exon_number 10 not 1!
> If this is the case then an easy solution for you is removing the "exon_number" field from the gtf. In this way velocyto will recalculate it internally.

**Comment by pangxueyu233** [comment]
@Suger0917 @gioelelm 
HI, I just met the same error. How to delete the "exon_number", I tried to use ```sed``` command to delete them, and I checked that all "exon_number" had been cleaned. But I still get an error that 
~~~
Traceback (most recent call last):
  File "/usr/local/bin/velocyto", line 9, in <module>
    load_entry_point('velocyto==0.17.17', 'console_scripts', 'velocyto')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/_run.py", line 212, in _run
    exincounter.mark_up_introns(bamfile=bamfile, multimap=multimap)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/counter.py", line 676, in mark_up_introns
    raise IOError(f"Input .bam file should be chromosome-sorted. (Hint: use `samtools sort {bamfile}`)")
OSError: Input .bam file should be chromosome-sorted. (Hint: use `samtools sort ('/mnt/data/macaque_control_1/outs/possorted_genome_bam.bam',)`)
~~~

And I also tried to use ```samtools sort -@ 40 -o ./outs/possorted_genome_bam.sorted.bam ./outs/possorted_genome_bam.bam 
``` and ```samtools index possorted_genome_bam.sorted.bam```. I still got the same errors as follwing:
~~~Traceback (most recent call last):
  File "/usr/local/bin/velocyto", line 9, in <module>
    load_entry_point('velocyto==0.17.17', 'console_scripts', 'velocyto')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/_run.py", line 212, in _run
    exincounter.mark_up_introns(bamfile=bamfile, multimap=multimap)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/counter.py", line 676, in mark_up_introns
    raise IOError(f"Input .bam file should be chromosome-sorted. (Hint: use `samtools sort {bamfile}`)")
OSError: Input .bam file should be chromosome-sorted. (Hint: use `samtools sort ('/mnt/data/macaque_control_1/outs/possorted_genome_bam.sorted.bam',)`)
~~~
Can you help me work it out? I have tried so many times 😭 😭 😭. And I really need these results to help me explore our data. I'm so expected for your suggestion

**Comment by liujian427** [comment]
> @Suger0917 @gioelelm HI, I just met the same error. How to delete the "exon_number", I tried to use `sed` command to delete them, and I checked that all "exon_number" had been cleaned. But I still get an error that
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/velocyto", line 9, in <module>
>     load_entry_point('velocyto==0.17.17', 'console_scripts', 'velocyto')()
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/run.py", line 116, in run
>     samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
>   File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/_run.py", line 212, in _run
>     exincounter.mark_up_introns(bamfile=bamfile, multimap=multimap)
>   File "/usr/local/lib/python3.6/dist-packages/velocyto/counter.py", line 676, in mark_up_introns
>     raise IOError(f"Input .bam file should be chromosome-sorted. (Hint: use `samtools sort {bamfile}`)")
> OSError: Input .bam file should be chromosome-sorted. (Hint: use `samtools sort ('/mnt/data/macaque_control_1/outs/possorted_genome_bam.bam',)`)
> ```
> 
> And I also tried to use `samtools sort -@ 40 -o ./outs/possorted_genome_bam.sorted.bam ./outs/possorted_genome_bam.bam ` and `samtools index possorted_genome_bam.sorted.bam`. I still got the same errors as follwing:
> 
> ```
>   File "/usr/local/bin/velocyto", line 9, in <module>
>     load_entry_point('velocyto==0.17.17', 'console_scripts', 'velocyto')()
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/run.py", line 116, in run
>     samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
>   File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/_run.py", line 212, in _run
>     exincounter.mark_up_introns(bamfile=bamfile, multimap=multimap)
>   File "/usr/local/lib/python3.6/dist-packages/velocyto/counter.py", line 676, in mark_up_introns
>     raise IOError(f"Input .bam file should be chromosome-sorted. (Hint: use `samtools sort {bamfile}`)")
> OSError: Input .bam file should be chromosome-sorted. (Hint: use `samtools sort ('/mnt/data/macaque_control_1/outs/possorted_genome_bam.sorted.bam',)`)
> ```
> 
> Can you help me work it out? I have tried so many times 😭 😭 😭. And I really need these results to help me explore our data. I'm so expected for your suggestion

@pangxueyu233 
Hi, I ran into the same problem when running this code.

velocyto run10x -m rheMac10_rmsk.gtf ./10X/ME24_count rheMac10.gtf

Have you solved it now? Thanks!

**Comment by denvercal1234GitHub** [comment]
> Hi, gioelelm. I followed your instruction and deleted the "exon_number" field. It worked perfectly!!! Thank you so much!
> 
> > Have you tried with different gtf files? For example with the ones downloaded from gencode?
> > I am not sure 100%, but I have a feeling that this is a notation issue...
> > If I remember correctly, the numbering of exons on strand minus "-" in gencode is the other way around.
> > For example for a gene with 10 exons the exon on the strand - at the 5' most of the reference sequence (that is always given on the + strand) should be exon_number 10 not 1!
> > If this is the case then an easy solution for you is removing the "exon_number" field from the gtf. In this way velocyto will recalculate it internally.

@Suger0917 -- Would you mind showing here how you delete the exon_number field from the genes.gtf file please? Thank you so much! I tried so many things so many times (#320) and none has worked for me.

**Comment by CristinaAlexandru** [comment]
In case this is still relevant to anyone, to remove "exon_number X", where X is a variable, you could try the following:

- assuming the "exon_number X" appears always as the 3rd field, i.e. `gene_id; transcript_id; exon_number`
- do `cut -f1-2,4- -d";" <(zcat geneset.gtfgz)`
- _cut_ is used here to extract all columns and fields from the last column, apart from field 3, where "exon_number X" would be.

**Comment by denvercal1234GitHub** [comment]
For me, it was not the issue with exon_number (see #320). Though, it still produced another error "Could not retrieve index file for the cellsorted_possorted_genome_bam.bam" yet the run10x still produced a loom file (#321). Any thoughts?
