### ISSUE TITLE
AttributeError: 'VelocytoLoom' object has no attribute 'colorandum'

### ISSUE THREAD

**Issue by linwang6** [velocyto-team/velocyto.py#128]
Hi velocyto teams,
When I perform the vlm.plot_grid_arrows command, it gives error:

>>> vlm.plot_grid_arrows(quiver_scale=0.6,scatter_kwargs_dict={"alpha":0.35, "lw":0.35, "edgecolor":"0.4", "s":38, "rasterized":True}, min_mass=24, angles='xy', scale_units='xy',headaxislength=2.75, headlength=5, headwidth=4.8, minlength=1.5,plot_random=True, scale_type="absolute")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xyy/conda3/lib/python3.6/site-packages/velocyto/analysis.py", line 2030, in plot_grid_arrows
    scatter_dict = {"s": 20, "zorder": -1, "alpha": 0.2, "lw": 0, "c": self.colorandum}
AttributeError: 'VelocytoLoom' object has no attribute 'colorandum'

How to fix it? Thanks so much!

**Comment by gioelelm** [comment]
The attribute is set automatically only if you define the clusters, otherwise, you need to assign an appropriate array manually

**Comment by gioelelm** [comment]
Dear @linwang6, 

As specified here: http://velocyto.org/velocyto.py/fullapi/api_analysis.html#velocyto.analysis.VelocytoLoom
All the information related to the cells are stored in the dictionary `vlm.ca`

**Comment by linwang6** [comment]
Hi gioelelm,

Thanks so much for your response. The vlm.pcs gives the PCA values, but there is no cell ID,
how to get corresponding cell ID using vlm.pcs?
>>> vlm.pcs[:,:2]
array([[ 12.17435869, -12.05161041],
       [ 16.13510536,  19.01448257],
       [ 13.0829138 ,  -8.50615262],
       ...,
       [ -7.39419943,  -1.28447384],
       [-10.4977947 ,   0.71154212],
       [ -6.12988906,  -3.23609731]])

Thanks.

**Comment by qinxuji** [comment]
Hi linwang, 

How did you fix this problem finally?

**Comment by qinxuji** [comment]
Hi @linwang6 ,
How did you fix this problem finally?
