### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (17983,) (17892,) 

### ISSUE THREAD

**Issue by linwang6** [velocyto-team/velocyto.py#134]
How fix this error, thanks.

>>> for gene in list_genes:
...     x = ds.layer["spliced"][np.where(ds.row_attrs["Gene"][:] == gene)[0][0], :]
...     x = np.mean(vlm.initial_cell_size) * x / vlm.initial_cell_size
...     list_s.append(x)
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ValueError: operands could not be broadcast together with shapes (17983,) (17892,) 

Does this means the shape of ds is different with vlm??

**Comment by linwang6** [comment]
Hi gioelelm, 
How to modify the loom file to make ds fit the vlm? 
Thanks.

**Comment by gioelelm** [comment]
I don't think you want to do that, that's your input data file... . Just
read data as numpy array and modify it in memory

**Comment by linwang6** [comment]
Thanks gioelelm, is there a example link or document for this, I didn't find it. Thanks.

**Comment by linwang6** [comment]
Hi gioelelm,
I did check the Complete API Reference, which one works for this, MemoryLoomLayer? Thanks.

create (function)
new (function)
create_from_cellranger (function)
connect (function)
combine (function)
LoomConnection (class)
LayerManager (class)
MemoryLoomLayer (class)
LoomLayer (class)
ViewManager (class)
LoomView (class)
LoomValidator (class)

**Comment by linwang6** [comment]
Hi gioelelm,
How to read the loom file as numpy array and modify it in memory? There is only loompy.connect for connecting loom file, not read the loom file in memory. Thanks.

**Comment by slinnarsson** [comment]
The documentation for loompy is at http://loompy.org

There are extensive tutorials and a detailed API reference that explain how to read and write loom files. Please start there, and if you get stuck, post an issue at the loompy repository.
