### ISSUE TITLE
Velocity on 5' scRNAseq

### ISSUE THREAD

**Issue by hawaiiki** [velocyto-team/velocyto.py#136]
Has velocyto been texted on the 10X 5' scRNAseq?

**Comment by hawaiiki** [comment]
I was able to get some 5' scRNAseq made with 10xgenomics and run the velocity on them.

**Comment by LikaiTan** [comment]
Hi hawiiki, I tested velocyto on my 10x 5' data, but I got very few counts from the loom file comparing to the original 10x matrix.  (please see [ issue#78](https://github.com/velocyto-team/velocyto.R/issues/78)).
May I know do you have the same problem?
