### ISSUE TITLE
The score_cv_vs_mean plot seems so weird?

### ISSUE THREAD

**Issue by linwang6** [velocyto-team/velocyto.py#143]
Hi Velocyto teams,

Thanks for providing this cool tool! I'm running sample using velocyto tool, but the score_cv_vs_mean plot seems very weird, not like the tutorial score_cv_vs_mean plot, please check the plot file, could you guys help to figure out the reasons, thanks!
[SCell_score_cv_vs_mean.pdf](https://github.com/velocyto-team/velocyto.py/files/2522519/SCell_score_cv_vs_mean.pdf)

**Comment by slinnarsson** [comment]
You’ve been hit by a [bug in Anaconda](
https://github.com/velocyto-team/velocyto.py/issues/104). It has been resolved in Anaconda 5.3. Update and you’ll be fine.

**Comment by linwang6** [comment]
Hi slinnarsson,

Here is the result,
Anaconda 5.3: 
      288.6749902572095 288.6749902572095
miniconda 4.4:
      288.6749902572095 288.6749902572095
It seems normal, right?

Is there any other reasons for this weird result? Thanks!

**Comment by slinnarsson** [comment]
Yes, then it’s not the Anaconda bug. Then I don’t have a solution at the moment.

**Comment by linwang6** [comment]
Hi slinnarsson,
Still working on this Fluidigm C1 data, if I performed the feature selection by vlm.filter_genes(by_cv_vs_mean=True), and I found that the marker genes were filtered out, so do the further analysis for the data set is meanless, if not perform the feature selection, does this matter? And also, it gives error in the plot_grid_arrows step:

>>> vlm.plot_grid_arrows(scatter_kwargs_dict={"alpha":0.7, "lw":0.7, "edgecolor":"0.4", "s":70, "rasterized":True},min_mass=2.9, angles='xy', scale_units='xy',headaxislength=2.75, headlength=5,headwidth=4.8, quiver_scale=0.35)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lwang6/miniconda3/lib/python3.6/site-packages/velocyto/analysis.py", line 2038, in plot_grid_arrows
    arrows_scale = np.percentile(np.linalg.norm(self.flow_rndm[self.total_p_mass >= min_mass, :], 2, 1), 90)  # Tipical lenght of an arrow
  File "/home/lwang6/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3540, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/home/lwang6/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3652, in _quantile_unchecked
    interpolation=interpolation)
  File "/home/lwang6/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3250, in _ureduce
    r = func(a, **kwargs)
  File "/home/lwang6/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3767, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/home/lwang6/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 181, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/lwang6/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

And in estimate_transition_prob step, it gives WARNING, 

>>> vlm.estimate_transition_prob(hidim="Sx_sz", embed="Pcs", transform="log", psc=1, n_neighbors=300, knn_random=True, sampled_fraction=1)
WARNING:root:Nans encountered in corrcoef and corrected to 1s. If not identical cells were present it is probably a small isolated cluster converging after imputation.
WARNING:root:Nans encountered in corrcoef_random and corrected to 1s. If not identical cells were present it is probably a small isolated cluster converging after imputation.

Could you give some advices? Thanks.

PS: How to set the neighbors number for small data (only 500 cells)? The giving examples in the tutorial used large numbers of cells for the analysis.  

Thanks.
