### ISSUE TITLE
QUESTION: running velocyto with multiple 10X files

### ISSUE THREAD

**Issue by cartal** [velocyto-team/velocyto.py#153]
Hi, 

velocyto is a fantastic tool and I'm very excited about it. 

My question is regarding running multiple 10X files. I have seen this question already in the issues but I think I have a different question:

At the moment I'm running velocyto run10x in a silly way:

`for i in $(cat samples.txt)
do
velocyto run10x -s sample_metadata.csv -@ 128 sample gencode.gtf
`
Here, the `sample_metadata.csv` file contains just the header and the information for a single sample. Now, this works fine if you have a couple of samples, but then it just becomes silly to create multiple csv files of metadata and I ended up having multiple loom files. 

I looked at the example for the SS2 data, and it looks like you could get away with a wildcard, but that was not the case for 10X. So, what is the proper way to do this when you have multiple 10X files? 

Thanks!

**Comment by gioelelm** [comment]
The metadata file can be just one and the same for all the calls.

**Comment by cartal** [comment]
Ok, I tried that before but then I got a syntax error complaining about the order of the files. 
I'll try again and update the issue. Thanks!

**Comment by cartal** [comment]
Problem solved. Thanks!
