### ISSUE TITLE
Another install problem

### ISSUE THREAD

**Issue by cap76** [velocyto-team/velocyto.py#158]
Hi,

Trying to install on python, but keep running into issues. If I try to install via pip3 install:
...
1 error generated.
error: command 'clang' failed with exit status 1

I won't post the full error message as others have encountered this, and the advice was to install via Conda. So I installed Conda. I tried pip install 

But get the error with "package_data: dict = {}" (again won't post full error message as this seems to have been posted and the advice was Conda). I thought that my pip was tied to my Conda, but might be msitaken.

Conda install velocyto gives me:

PackagesNotFoundError: The following packages are not available from current channels:

  - velocyto

If I trie to install via R, I get a popup telling me to install additional build tools :-(

**Comment by gioelelm** [comment]
It might be related to the compilers somehow, or simply with your conda
env... I would suggest :

Make sure you are using conda for python3.

Make sure you explicitly install dependencies as in the instructions.

Run: conda install llvm gcc libgcc

Check that 'which pip' points to the conda pip

Now run pip install velocyto

**Comment by cap76** [comment]
Hi gioelelm,

Thanks for the message. I was thinking that the compilers are playing up somewhere, but will check out the python env first and get back to you :-)

**Comment by cap76** [comment]
Okay, managed to create an environment where this installs:

conda create -n my_py_env python=3.6.6
conda install numpy scipy cython numba matplotlib scikit-learn h5py click

which -a pip
		/anaconda3/envs/my_py_env/bin/pip
		/anaconda3/bin/pip

/anaconda3/envs/my_py_env/bin/pip install pysam

conda install llvm gcc libgcc

python --version
		Python 3.6.6 :: Anaconda, Inc.

/anaconda3/envs/my_py_env/bin/pip install velocyto

Feel free to close, although will post if I manage to resolve the R install.
