### ISSUE TITLE
ModuleNotFoundError: No module named 'velocyto.speedboosted'

### ISSUE THREAD

**Issue by somnathtagore** [velocyto-team/velocyto.py#166]
Hi.. i installed velocyto on HPC cluster and it was fine.. but now when i do 

$ velocyto --help
Traceback (most recent call last):
  File "/....../anaconda3/envs/my_pymc_env/bin/velocyto", line 7, in <module>
    from velocyto.commands.velocyto import cli
  File "/...../rna-velocity/velocyto.py/velocyto/__init__.py", line 13, in <module>
    from .estimation import fit_slope, _fit1_slope, clusters_stats
  File "/....../rna-velocity/velocyto.py/velocyto/estimation.py", line 7, in <module>
    from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
ModuleNotFoundError: No module named 'velocyto.speedboosted'

I used conda for all installation

**Comment by somnathtagore** [comment]
Hi ... 
$which -a cython
~/anaconda3/envs/my_pymc_env/bin/cython
~/anaconda3/bin/cython

$ cython --version
Cython version 0.29.2

**Comment by gioelelm** [comment]
I just noticed that you wrote

“”"I used conda for all installation”””

You mean conda for the dependencies and pip for Velocyto right? (I did not create a conda recipe, but I don’t know if a third party does)

Anyways even if that was right and Cython is installed It remains the fact that the submodule was not installed, so something did go wrong!
Could you try to uninstall and reinstall with a verbose flag and check how the installation goes.
Also, try to run

conda instal gcc,libgcc, cython

just before the reinstallation to be sure, everything necessary is installed/updated.

If this also fails, uninstall again, git clone the repo and install from source running:

cd velocyto.py
pip install -e .

Also there, keep an eye on the output!

Please keep me posted on whether it works.

**Comment by somnathtagore** [comment]
Hi,

the issue was sorted... i uninstalled and again installed! ...

thanks!
