### ISSUE TITLE
'show.velocity.on.embedding.cor' error

### ISSUE THREAD

**Issue by somnathtagore** [velocyto-team/velocyto.py#169]
Hi, 

I am running velocyto on https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_1k_v2...

But, i am getting this error...

show.velocity.on.embedding.cor(emb,rvel.cd,n=600,scale='sqrt',cell.colors=ac(cell.colors,alpha=0.5),cex=0.8,arrow.scale=5,
+                                show.grid.flow=TRUE,
+                                min.grid.cell.mass=0.5,grid.n=40,arrow.lwd=1,do.par=F,cell.border.alpha = 0.1)
delta projections ... sqrt knn ... transition probs ... done
calculating arrows ... grid estimates ... Error in seq.default(rx[1], rx[2], length.out = grid.n) : 
  'from' must be a finite number

Can you please help ?

Many thanks!

**Comment by somnathtagore** [comment]
Hi,

I have managed to remove this error...
we can do:
emat <- emat[,colSums(is.na(emat))<nrow(emat)] to remove all NAs.

Many thanks!

**Comment by yuanG2000** [comment]
hi, I have the same problem.
Could you please tell me what emat is ,in your solution.
thanks a lot
