### ISSUE TITLE
Issue with group_constraint option in knn_imputation

### ISSUE THREAD

**Issue by Thopic** [velocyto-team/velocyto.py#173]
Hi, 

I'm using velocyto to look at RNA velocities in cells coming from different patients. I reunited all the loom files in one and I'm importing the clusters names from a previous analysis (Seurat). It's working well and I'm quite impressed by your library,

I don't want cells from different patients to be thought as "neighbours" during velocyto pipeline, so I want to use the option `group_constraint` of the function `knn_imputation` with an array of int, of size `vlm.S.shape[1]`, which associate to each cell an integer corresponding to its patient of origin.

But when I try to use it this way, I receive the error: 
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-52-d5a186507017> in <module>
      5 vlm.perform_PCA()
      6 vlm.knn_imputation(n_pca_dims=15, balanced=True, 
----> 7                   group_constraint=vlm.ca["patient"])

~/.local/lib/python3.7/site-packages/velocyto/analysis.py in knn_imputation(self, k, pca_space, metric, diag, n_pca_dims, maximum, size_norm, balanced, b_sight, b_maxl, group_constraint, n_jobs)
    995                 if isinstance(group_constraint, str) and group_constraint == "clusters":
    996                     constraint = np.array(self.cluster_ix)
--> 997                 bknn = BalancedKNN(k=k, sight_k=b_sight, maxl=b_maxl, metric=metric, constraint=constraint, mode="distance", n_jobs=n_jobs)
    998             else:
    999                 bknn = BalancedKNN(k=k, sight_k=b_sight, maxl=b_maxl, metric=metric, mode="distance", n_jobs=n_jobs)
UnboundLocalError: local variable 'constraint' referenced before assignment
```
Without the option, everything works fine. 
If I'm not mistaken, I think that the issue comes from the fact that the variable `constraint` is only defined if `group_constraint` is an `str` object. An easy fix would be to add two lines after line 996 of `analysis.py`:

```
if(isinstance(group_constraint, ndarray)):
    constraint = group_constraint
```
I can create a pull request if you prefer,

Additionally, do you think this is the "right" way to apply velocyto on multi-sample data, if I want to be able to compare samples ? Is there any other pitfall I should be aware of in that kind of analysis ?

Thanks for your excellent package,

Thomas

**Comment by gioelelm** [comment]
Thank you for reporting. It solved in version 0.17.17, but notice it does not check the formatting of the array passed so it is the responsibility of the user to understand what needs to be passed (an integers array of labels without gaps, as returned by np.unique(return_inverse=True))

**Comment by Thopic** [comment]
Thanks, it works, I didn't see that there was a 0.17.17

**Comment by gioelelm** [comment]
There wasn’t I made it to fix the bug you reported!

**Comment by Thopic** [comment]
Wow that was fast, thanks again !

**Comment by denvercal1234GitHub** [comment]
Hi @Thopic -- Thank you for a detailed question above. I wonder if you would not mind explaining why you would not want "cells from different patients to be thought as "neighbours" during velocyto pipeline"? Is it because you want to analyze each donor individually? 

I also have 3 donors, and each donor has 2 different cell populations which were sorted and sequenced. I have also merged the loom files into 1 loom file (btw, do we need some kind of batch correction?).
