### ISSUE TITLE
segmentation fault in conda environment

### ISSUE THREAD

**Issue by whtns** [velocyto-team/velocyto.py#175]
I installed velocyto [as recommend](https://velocyto.org/velocyto.py/install/index.html) using a mixture of conda and pip commands. I initially received a segmentation fault error each time I ran from CLI or imported velocyto in python. 

I was able to resolve the issue by updating [sip](https://anaconda.org/anaconda/sip) and [pyqt](https://anaconda.org/anaconda/pyqt) in conda. I don't know why this worked. I am not knowledgeable about python interfacing with C or C++. Just thought I would document in case others ran across this same issue.

**Comment by gioelelm** [comment]
I suspect it was related somehow to the import of matplotlib functions that happens within velocyto. pyqt can be imported only by matpltolib of the libraries I use...as far as I know at least

**Comment by dawe** [comment]
I'm having (possibly) the same issues (core dump). I've tried to go with python debugger and I found velocyto crashes at the very beginning, calling 
```load_entry_point('velocyto==0.17.16', 'console_scripts', 'velocyto')()
``` 
in `__init__.py`. The actual function that crashes is 
```
module = __import__(self.module_name, fromlist=['__name__'], level=0)
```
from `pkg_resources` 
The last message from `gdb -ex r --args python ~/.local/bin/velocyto ` is

```
PyType_IsSubtype (a=0x626f6174656d5f74, b=0x2aaac9cba680)
    at /home/conda/feedstock_root/build_artifacts/python_1542767440920/work/Objects/typeobject.c:1357
1357    /home/conda/feedstock_root/build_artifacts/python_1542767440920/work/Objects/typeobject.c: No such file or directory.
        in /home/conda/feedstock_root/build_artifacts/python_1542767440920/work/Objects/typeobject.c
```

I'm trying to debug myself, but I'm having issues with the python support in gdb

**Comment by gioelelm** [comment]
Unfortunately, your traceback are quite cryptic to me
Maybe try conda install gcc, libgcc
(make sure conda is downloading the conda-forge version)

I reinstalled velocyto from scratch recently on two new machines, I was starting with a fresh anaconda install and adding conda-forge and bioconda immediately to my channels and everything went well. So I am thinking the problem could be a conflict with the previously installed version of libraries, or some breaking changes in matplotlib.

**Comment by dawe** [comment]
I believe it may be due to the gcc compiler not properly linking stuff. I'm trying to fix this. Hopefully it is only an issue on my hardware

**Comment by gioelelm** [comment]
Yeah but your conda installation should be using its own compiler that is sandboxed, if it using your systems one there is a problem IMHO

**Comment by dawe** [comment]
Right, but I've just discovered that my conda gcc was not compatible with our cluster. In the past I've compiled most of the packages using system gcc, but for velocyto this didn't work (I suspect for OpenMP support).
See this https://github.com/conda/conda-recipes/pull/279
I've reinstalled gcc and I can now reproduce the error at the beginning of this issue
```
$ velocyto 
Traceback (most recent call last):
  File "/home/dcittaro/.local/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto==0.17.16', 'console_scripts', 'velocyto')()
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dcittaro/.local/lib/python3.6/site-packages/velocyto-0.17.16-py3.6-linux-x86_64.egg/velocyto/__init__.py", line 15, in <module>
    from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b, load_velocyto_hdf5
  File "/home/dcittaro/.local/lib/python3.6/site-packages/velocyto-0.17.16-py3.6-linux-x86_64.egg/velocyto/analysis.py", line 10, in <module>
    import matplotlib.pyplot as plt
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

I'm using Tk as matplotlib backend, I'll check if somewhere in velocyto I can force this

**Comment by gioelelm** [comment]
Ok, now it makes sense.
I am afraid I cannot offer support myself for non-standard installation scenarios, the only way I can effectively bugfix users problems is by forcing some constraints onto the installation environment.

I will keep following the issue tread, in case I can provide help.
I would greatly appreciate if you post here solution here if you happen to find it! Other users might find it useful!

**Comment by dawe** [comment]
I've been able to run velocyto modifying the `analysis.py` source

```diff --git a/velocyto/analysis.py b/velocyto/analysis.py
index eeae8e7..5c99213 100644
--- a/velocyto/analysis.py
+++ b/velocyto/analysis.py
@@ -7,6 +7,7 @@ from scipy.stats import norm as normal
 import scipy.stats
 from scipy import sparse
 import matplotlib
+matplotlib.use('tkagg')
 import matplotlib.pyplot as plt
 from sklearn.svm import SVR
 from sklearn.decomposition import PCA
```

I guess a better way would be a try/catch statement for `import matplotlib.pyplot as plt`, as it may fail loading on some systems. I'm pretty sure I've seen this before somewhere else, there should be an elegant solution

**Comment by gioelelm** [comment]
Wow, that was fast!
Yes, even though  I think I should still raise an error but with a clearer error message specifying what it is not working and suggesting the user a change of backend to tkagg in the matplotlibrc file.... After all since qt as a whole is failing to be imported, the user will want to avoid this problem at his installation level instead of it having velocyto patching it silently.
