### ISSUE TITLE
Residuals and expression intensity

### ISSUE THREAD

**Issue by kaizen89** [velocyto-team/velocyto.py#189]
Is there a way to show the residuals for a given gene and at the same time show the level of exppression in each cell? Maybe by multiplying the residuals by the level on unspliced reads?

**Comment by gioelelm** [comment]
I am not sure if you are looking for a pre build function or just the data to plot.The residuals are stored in `vlm.velocity`And expression in `vlm.Sx_sz` and `vlm.Ux_sz`Plotting functions that plot expression and residuals on the embedding are: `vlm.plot_expression_as_color` `vlm.plot_velocity_as_color`Sent from my mobile - excuse the typos
