### ISSUE TITLE
'CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by chris-mcginnis-ucsf** [velocyto-team/velocyto.py#190]
Hello!

After getting velocyto running in my Mac OS environment, I am now trying to repeat the process on our linux server due to memory issues when running locally. 

(1) I first installed Anaconda linux distribution for Python 3.7 :

[chris@CAT-EPYC Velocyto]$ conda -V
conda 4.6.11
[chris@CAT-EPYC Velocyto]$ python -V
Python 3.7.3

(2) I then created and activated a new conda environment:

conda create -n velo python=3.7
conda activate velo

(3) I then installed dependencies according to the tutorial + github threads:

conda install numpy scipy cython numba matplotlib scikit-learn h5py click gcc libgcc llvm cython pip -c conda-forge
pip install pysam
pip insall velocyto

(4) I then checked the installation status:

(velo) [chris@CAT-EPYC Velocyto]$ conda list
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/chris/.conda/envs/velo:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0  
certifi                   2019.3.9                 py37_0  
click                     7.0                        py_0    conda-forge
cloog                     0.18.0                        0  
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.7           py37he1b5a44_0    conda-forge
dbus                      1.13.2               h714fa37_1  
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gcc                       4.8.5                         7  
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0           nompi_py37hf008753_1102    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
isl                       0.12.2                        0  
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
llvm                      3.3                           0  
llvmlite                  0.28.0           py37hdbcaa40_0    conda-forge
loompy                    2.0.17                   pypi_0    pypi
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37h167e16e_0    conda-forge
mpc                       1.1.0                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
ncurses                   6.1                  he6710b0_1  
numba                     0.43.1           py37he1b5a44_0    conda-forge
numpy                     1.15.4          py37h8b7e671_1002    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h7b6447c_1  
pandas                    0.24.2                   pypi_0    pypi
pcre                      8.43                 he6710b0_0  
pip                       19.0.3                   py37_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pysam                     0.15.2                   pypi_0    pypi
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                   pypi_0    pypi
qt                        5.6.3                h8bf5577_3  
readline                  7.0                  h7b6447c_5  
scikit-learn              0.20.3           py37ha8026db_1    conda-forge
scipy                     1.2.1            py37h09a28d5_1    conda-forge
setuptools                41.0.0                   py37_0  
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.27.2               h7b6447c_0  
system                    5.8                           2  
tk                        8.6.9             h84994c4_1001    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
velocyto                  0.17.17                  pypi_0    pypi
wheel                     0.33.1                   py37_0  
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  

[chris@CAT-EPYC Velocyto]$ pip install pysam
Requirement already satisfied: pysam in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (0.15.2)

[chris@CAT-EPYC Velocyto]$ pip install velocyto
Requirement already satisfied: velocyto in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (0.17.17)
Requirement already satisfied: Click in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (7.0)
Requirement already satisfied: cython in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (0.29.7)
Requirement already satisfied: loompy in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (2.0.17)
Requirement already satisfied: scipy in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (1.2.1)
Requirement already satisfied: pysam in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (0.15.2)
Requirement already satisfied: numpy in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (1.15.4)
Requirement already satisfied: scikit-learn in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (0.20.3)
Requirement already satisfied: h5py in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (2.9.0)
Requirement already satisfied: numba in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (0.43.1)
Requirement already satisfied: matplotlib in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (3.0.3)
Requirement already satisfied: pandas in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from velocyto) (0.24.2)
Requirement already satisfied: setuptools in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from loompy->velocyto) (41.0.0)
Requirement already satisfied: six in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from h5py->velocyto) (1.12.0)
Requirement already satisfied: llvmlite>=0.28.0dev0 in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from numba->velocyto) (0.28.0)
Requirement already satisfied: cycler>=0.10 in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from matplotlib->velocyto) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from matplotlib->velocyto) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from matplotlib->velocyto) (2.4.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from matplotlib->velocyto) (2.8.0)
Requirement already satisfied: pytz>=2011k in /home/chris/.conda/envs/velo/lib/python3.7/site-packages (from pandas->velocyto) (2019.1)

This is the same workflow with which I got Velocyto working in Mac OS (note: due to Mojave update, I needed to also do sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target / ). However when I test velocyto on the server, I get the following error:

(velo) [chris@CAT-EPYC Velocyto]$ velocyto --help
Traceback (most recent call last):
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typeconv/typeconv.py", line 6, in <module>
    from . import _typeconv
ImportError: /home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typeconv/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typeconv/_typeconv.cpython-37m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/.conda/envs/velo/bin/velocyto", line 6, in <module>
    from velocyto.commands.velocyto import cli
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/velocyto/__init__.py", line 12, in <module>
    from .neighbors import BalancedKNN, convolve_by_sparse_weights
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/velocyto/neighbors.py", line 2, in <module>
    from numba import jit
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/__init__.py", line 14, in <module>
    from .special import typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/special.py", line 3, in <module>
    from .typing.typeof import typeof
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typing/__init__.py", line 2, in <module>
    from .context import BaseContext, Context
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typing/context.py", line 12, in <module>
    from numba.typeconv import Conversion, rules
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typeconv/rules.py", line 3, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typeconv/typeconv.py", line 16, in <module>
    raise ImportError(msg)
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: '/home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typeconv/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/chris/.conda/envs/velo/lib/python3.7/site-packages/numba/typeconv/_typeconv.cpython-37m-x86_64-linux-gnu.so)'

I'm pretty new to the conda/python world and feel like troubleshooting this error is a bit beyond my skillset. Do you have any advice?

Chris

**Comment by chris-mcginnis-ucsf** [comment]
bump?

**Comment by gioelelm** [comment]
It is a compiler problem. We have been getting many similar issues.
Some of the ones that might be related:
#187,  #186 , #175, #171, #108, #104, #98 , #88 , #74 , #72 , #53 , #46 , #36 , #25 , 

Since I have no new solutions to offer you should first try those proposed solutions and the we can take it from there. 

Some of the most common suggestions that lead to the solution of the problem quite often:
- I reccomand always a fresh install of conda
- I recommend the usage of conda-forge and bioconda channels
- I recommend to run on the root/main environment (I can't explain why but switching from an environment to main tend to solve compiler problems to me)
- Try to run `conda install llvm gcc lib-gcc cython`
- Try to check which one is the default compiler in your root environment, should be the conda one not the system one

**Comment by chris-mcginnis-ucsf** [comment]
Thanks for the reply. 

To close the loop on this, I ended up finding a solution outside of the velocyto-related issues threads. Specifically, installing gcc v4.9 fixed the problem (see https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found).

So my installation/running workflow (note: on linux system) was as follows:

1. Install anaconda with python v3.7
2. Create conda environment: conda create -n velo python=3.7
3. Activate conda environment: conda activate velo
4. Install dependencies through conda forge channel: 
conda install numpy scipy cython numba matplotlib scikit-learn h5py click llvm pip libgcc -c conda-forge
5. Install gcc version 4.9: conda install -c serge-sans-paille gcc_49 
6. Install samtools through bioconda channel: conda install -c bioconda samtools 
7. Direct install pysam: pip install pysam
8. Direct install velocyto: pip install velocyto
9. Upload CellRanger reference GTF and masked GTF to server
10. Upload barcode tsv file for singlets (I removed doublets using MULTI-seq and DoubletFinder)
11. Run velocyto: velocyto run -b /path/to/barcodes_singlets.tsv -o /path/to/out -m /path/to/mm10_3.0.0_rmsk.gtf /path/to/possorted_genome_bam.bam /path/to/mm10_3.0.0_genes.gtf

Chris

**Comment by jacobluber** [comment]
The following should fix all of the Mac compiler issues that @gioelelm mentioned:
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
cd /Library/Developer/CommandLineTools/Packages/
open macOS_SDK_headers_for_macOS_10.14.pkg
```

**Comment by liuzhe93** [comment]
> 8\. velocyto

hi! This is liuzhe. Thanks for reading this email. I got a error information when I install the velocyto.py. My scripts are as yours:

Install anaconda with python v3.7
Create conda environment: conda create -n velo python=3.7
Activate conda environment: conda activate velo
Install dependencies through conda forge channel:
conda install numpy scipy cython numba matplotlib scikit-learn h5py click llvm pip libgcc -c conda-forge
Install gcc version 4.9: conda install -c serge-sans-paille gcc_49
Install samtools through bioconda channel: conda install -c bioconda samtools
Direct install pysam: pip install pysam
Direct install velocyto: pip install velocyto
When I install veloyto using pip, I got the question as follows:
>pip install velocyto
gcc: error: unrecognized command line option ‘-fPIC -L/home/bin/bzip2-1.0.6/lib’
error: command 'gcc' failed with exit status 1
>python --version
#Python 3.7.10
>gcc --version
#gcc (GCC) 4.9.1
#Copyright (C) 2014 Free Software Foundation, Inc.
#This is free software; see the source for copying conditions.  There is NO
#warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Could you give me some suggestions. Thanks in advance. 

With my best wishes,
liuzhe
