### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by annajbott** [velocyto-team/velocyto.py#208]
Hi, 
I'm trying to run velocyto for DropSeq data, but having some issues generating a loom file. Currently I am using the general velocyto run command. I've tried it with and without masked regions specified, and have now included a whitelist of CBs.
Run command is as follows:

```velocyto run -b velocyto.dir/N701_WT_barcodes.tsv -o ./velocyto.dir -e N701_WT -m hg38_rmsk.gtf velocyto.dir/N701_WT.bam geneset_all.gtf```

I am using a pipeline to run multiple samples, but performed the step: ```samtools sort -t CB ``` prior to running velocyto as suggested in the documentation.

However I keep getting an error about MemoryError. More specifically:
``` File "/ifs/devel/annajb/conda-install/envs/cgat-f/bin/velocyto", line 11, in <module> sys.exit(cli())
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/click/core.py", line 764, in  __call__
    return self.main(*args, **kwargs)
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/velocyto/commands/_run.py", line 229, in _run
    results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evaluations if we write two function count and count_with output
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/velocyto/counter.py", line 761, in count
    dict_layer_columns, list_bcs = self.count_cell_batch()
  File "/ifs/devel/annajb/conda-install/envs/cgat-f/lib/python3.6/site-packages/velocyto/counter.py", line 845, in _count_cell_batch_stranded
    dict_layers_columns[layer_name] = np.zeros(shape, dtype=self.loom_numeric_dtype, order="C") 
MemoryError 
```

I am using a cluster and have given the job 75G and I am still getting this error.
I have installed the latest versions of  h5py and loompy using conda and I am using samtools version 1.9. 

Additionally from what I've seen from other people's output they are getting <100 batches, however in my log I seem to be getting upwards of 10000 batches being counted all containing 100 cells. My experiment was not very large, ranging between 400 cells-1500 cells per sample. 
Any advice on what I might be doing wrong? If you need more information, don't hesitate to ask! Any help would be very much appreciated!

Thanks,
Anna

**Comment by annajbott** [comment]
I was thinking maybe I've made a mistake somewhere in pre-processing of the data to make it ready to use with velocyto. Here are some example lines from each file.

Example line from my annotation gtf file:
```
chr1    havana  exon    13221   14409   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; exon_number "3"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; havana_gene "OTTHUMG00000000961"; havana_gene_version "2"; transcript_name "DDX11L1-002"; transcript_source "havana"; transcript_biotype "processed_transcript"; havana_transcript "OTTHUMT00000362751"; havana_transcript_version "1"; exon_id "ENSE00002312635"; exon_version "1"; tag "basic"; transcript_support_level "1";
```
Example lines from bcfile:
```
CAGAACTAGTAA
CACGCTCGCCGG
CTCACGTGCGAC
ACAACACCTAAA
```
Example lines from BAM file:
```
NS500377:389:HGC7YBGXB:2:22106:26271:3278       16      chr1    14357   1       50M     *       0       0       TTGCATCCTGCACAGCTAGAGATCCTTTATTAAAAGCACACTGTTGGTTT      /EAEEEEEEAEEEEEEEEEEEEEEEEE/EAEEEEEEEEEEEEEEEAAAAA      NH:i:4  HI:i:1  AS:i:49 nM:i:0  XC:Z:TATTGCGTTTAG       XM:Z:AAGTTCGT
NS500377:389:HGC7YBGXB:1:23309:13803:7365       16      chr1    14359   1       30M     *       0       0       GCATCCTGCACAGCTAGAGATCCTTTATTA  EEEEEEEEEEEEEEEEEEEEEEEEAAAA6A  NH:i:4  HI:i:1  AS:i:29 nM:i:0  XC:Z:GGGCGTAACTGG       XM:Z:TGTCTAGG   ZP:i:31
NS500377:390:HGCCGBGXB:1:21203:6781:6066        16      chr1    14359   1       30M     *       0       0       GCATCCTGCACAGCTAGAGATCCTTTATTA  /EEEEEAEEEE6E/EEEEEEEE6EE/AAAA  NH:i:4  HI:i:1  AS:i:29 nM:i:0  XC:Z:GGGCGTAACTGG       XM:Z:TGTCTAGG   ZP:i:31
```

Example lines from mask file:
```
chr1    hg38_rmsk       exon    67108754        67109046        1892.000000     +       .       gene_id "L1P5"; transcript_id "L1P5"; 
chr1    hg38_rmsk       exon    8388316 8388618 2582.000000     -       .       gene_id "AluY"; transcript_id "AluY"; 
chr1    hg38_rmsk       exon    25165804        25166380        4085.000000     +       .       gene_id "L1MB5"; transcript_id "L1MB5"; 
```

Are there any glaringly obvious mistakes?

Thanks again,
Anna

**Comment by annajbott** [comment]
Sorted the issue. I was using XC and XM tags as these are required for a picard programme I am using. However, later steps require the CB tag instead of XC (samtools sort -t CB ...  and  --bcfile needs CB tags), so after aligning the reads, I converted the tags to UB and CB.
The documentation states the input file will have to:  _Contain an error corrected cell barcodes as a TAG named CB or XC._ 
I think it should be more explicitly stated in the documentation that although XC/XM are fine, later you are required to use CB for certain steps in velocyto run.

**Comment by denvercal1234GitHub** [comment]
@annajbott -- Thanks for pointing out the errors. Would you mind giving the codes to align the reads and convert the tags? And how did you check the tags for the bam files? Thank you so much!

**Comment by annajbott** [comment]
Hi, 
It was quite a while a go so my memory isn't great, but I made a pipeline out of it at the time, I think its this task:
https://github.com/cribbslab/scflow/blob/master/scpipelines/pipeline_velocyto.py#L337

This python file of the task does it I think:
https://github.com/cribbslab/scflow/blob/master/scpipelines/pipeline_velocyto/python/MergeBam.py

I've had issues with pysam versions before. Usually 0.15.2 seems to work okay with my environment. Hope this helps.

Best,
Anna
