### ISSUE TITLE
Dictionary KeyError in extract_intervals

### ISSUE THREAD

**Issue by erinhwilson** [velocyto-team/velocyto.py#22]
Hey! I've installed velocyto and am looking to use it to create the ivls.txt file from a gtf. In particular, I'm trying to use the ensembl human genome gtf here: http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/ 

I started the process with the following command: 
`velocyto extract_intervals Homo_sapiens.GRCh37.75.gtf -p GRCh37
`
And it starts running but then after about 2 hours, it failed with what I think is a dictionary lookup error for a gene name? Here is the traceback:

```
2017-11-16 23:45:55,547 - DEBUG - 47500 genes already processed
2017-11-16 23:51:16,930 - DEBUG - 50000 genes already processed
2017-11-16 23:56:46,434 - DEBUG - 52500 genes already processed
Traceback (most recent call last):
  File "/home/ubuntu/ebs/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/velocyto/commands/extract_intervals.py", line 152, in extract_intervals
    othertrs.update(binnedtrs_by_chromstrand[chromstrand][trbin])
KeyError: 'HG1007_PATCH+'
```

I looked into the Homo_sapiens.GRCh37.75.gtf file and could not find the pattern 'HG1007_PATCH+' but I did find it several times without the '+' (just 'HG1007_PATCH'). I'm wondering if there is a chance the + got accidentally attached to the gene name when it was defined as a dictionary key at some point? Or if you have any suggestions for finding where this gene name edit might have happened?

Thanks!

**Comment by gioelelm** [comment]
Could you report some examples of the lines that present  occurrences of "HG1007_PATCH"?
Something like the output of: ``cat Homo_sapiens.GRCh37.75.gtf | grep HG1007_PATCH  | head -n 100``

Notice the "+" is not the problem here and is just indicating the strand. 
What you faced is probably a parsing problem, where I make some wrong assumption on what the chromosome name should look like.

**Comment by erinhwilson** [comment]
Sure! Here are all the lines with HG1007_PATCH:

HG1007_PATCH	pseudogene	gene	243062007	243062204	.	-	gene_id "ENSG00000262743"; gene_name "CICP10"; gene_source "havana"; gene_biotype "pseudogene";
HG1007_PATCH	processed_pseudogene	transcript	243062007	243062204	gene_id "ENSG00000262743"; transcript_id "ENST00000575956"; gene_name "CICP10"; gene_source "havana"; gene_biotype "pseudogene"; transcript_name "CICP10-001"; transcript_source "havana";
HG1007_PATCH	processed_pseudogene	exon	243062007	243062204	.	gene_id "ENSG00000262743"; transcript_id "ENST00000575956"; exon_number "1"; gene_name "CICP10"; gene_source "havana"; gene_biotype "pseudogene"; transcript_name "CICP10-001"; transcript_source "havana"; exon_id "ENSE00002631565";
HG1007_PATCH	pseudogene	gene	243064438	243064620	.	+	gene_id "ENSG00000261859"; gene_name "AC134873.1"; gene_source "havana"; gene_biotype "pseudogene";
HG1007_PATCH	processed_pseudogene	transcript	243064438	243064620	gene_id "ENSG00000261859"; transcript_id "ENST00000570774"; gene_name "AC134873.1"; gene_source "havana"; gene_biotype "pseudogene"; transcript_name "AC134873.1-001"; transcript_source "havana";
HG1007_PATCH	processed_pseudogene	exon	243064438	243064620	.	gene_id "ENSG00000261859"; transcript_id "ENST00000570774"; exon_number "1"; gene_name "AC134873.1"; gene_source "havana"; gene_biotype "pseudogene"; transcript_name "AC134873.1-001"; transcript_source "havana"; exon_id "ENSE00002662146";
HG1007_PATCH	pseudogene	gene	243117332	243117785	.	+	gene_id "ENSG00000271453"; gene_name "ABC7-43041300I9.1"; gene_source "havana"; gene_biotype "pseudogene";
HG1007_PATCH	processed_pseudogene	transcript	243117332	243117785	gene_id "ENSG00000271453"; transcript_id "ENST00000603113"; gene_name "ABC7-43041300I9.1"; gene_source "havana"; gene_biotype "pseudogene"; transcript_name "ABC7-43041300I9.1-001"; transcript_source "havana";
HG1007_PATCH	processed_pseudogene	exon	243117332	243117785	.	gene_id "ENSG00000271453"; transcript_id "ENST00000603113"; exon_number "1"; gene_name "ABC7-43041300I9.1"; gene_source "havana"; gene_biotype "pseudogene"; transcript_name "ABC7-43041300I9.1-001"; transcript_source "havana"; exon_id "ENSE00003588744";

**Comment by pl-ki** [comment]
I fixed this issue by ignoring all patched chromosomes  - they are in any case not included in the alignments. Please try now.

**Comment by pl-ki** [comment]
Note this fix is a branch 'ivlpatch' currently, will be merged later

**Comment by erinhwilson** [comment]
Great thanks so much! It looks like it finished processing all the genes this time around! I got a different error (looks like it's trying to close the file fd but fd wasn't defined in this scope?) but I think it might have happened after the ivls file was produced? Is there any way to check the ivls.txt file to make sure it's complete?

Here's the new error:
```
Traceback (most recent call last):
  File "/home/ubuntu/ebs/anaconda3/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/ebs/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/ebs/workspace/velocyto.py/velocyto/commands/extract_intervals.py", line 291, in extrac
t_intervals
    fd.close()
NameError: name 'fd' is not defined
```

**Comment by pl-ki** [comment]
This file closing is the last step before finishing, so the file should be intact. I fixed this stupid bug.

**Comment by erinhwilson** [comment]
Perfect, thanks again!
