### ISSUE TITLE
Error reading in loom file

### ISSUE THREAD

**Issue by genomics-kl** [velocyto-team/velocyto.py#222]
Hello,

I am getting an error trying to read in a loom file produced using 'run10x' (version 0.17.17). Interestingly, this error only happens with velocyto.py; I can read in the loom file using the R implementation of velocyto and run the downstream analyses. Would really appreciate some advice about what might be going on.

**CLI command for making loom file:**
velocyto run10x \
-@ 8 \
-m mm10_rmsk.gtf \
/cellranger_count/sample1 \
genes.gtf

**Command to read in loom file:**
adata = scv.read("./data2/Arm_CD8_Day15.loom", cleanup=True, sparse=True, cache=True)

**Last several lines from the traceback:**
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'attrs' doesn't exist)"

**Comment by slinnarsson** [comment]
Have you recently upgraded loompy? It might be related to recent changes to the loom file format. Can you paste the full stack trace?

**Comment by genomics-kl** [comment]
Yes, running 'loompy.__version__' shows 3.0.4. The full trace is below:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-1d875163c9d9> in <module>
      1 import velocyto as vcy
----> 2 vlm = vcy.VelocytoLoom("./data2/sample1.loom")

/miniconda2/envs/jupyter/lib/python3.7/site-packages/velocyto/analysis.py in __init__(self, loom_filepath)
     56     def __init__(self, loom_filepath: str) -> None:
     57         self.loom_filepath = loom_filepath
---> 58         ds = loompy.connect(self.loom_filepath)
     59         self.S = ds.layer["spliced"][:, :]
     60         self.U = ds.layer["unspliced"][:, :]

/miniconda2/envs/jupyter/lib/python3.7/site-packages/loompy/loompy.py in connect(filename, mode, validate, spec_version)
   1387                 Note: if validation is requested, an exception is raised if validation fails.
   1388 	"""
-> 1389         return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)

/miniconda2/envs/jupyter/lib/python3.7/site-packages/loompy/loompy.py in __init__(self, filename, mode, validate, spec_version)
     79                 if validate:
     80                         lv = loompy.LoomValidator(version=spec_version)
---> 81                         if not lv.validate(filename):
     82                                 raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")
     83 

/miniconda2/envs/jupyter/lib/python3.7/site-packages/loompy/loom_validator.py in validate(self, path, strictness)
     46                 valid1 = True
     47                 with h5py.File(path, mode="r") as f:
---> 48                         valid1 = self.validate_spec(f)
     49                         if not valid1:
     50                                 self.errors.append("For help, see http://linnarssonlab.org/loompy/format/")

/miniconda2/envs/jupyter/lib/python3.7/site-packages/loompy/loom_validator.py in validate_spec(self, file)
    199                 if self.version == "3.0.0":
    200                         self._check("attrs" in file, "Global attributes missing")
--> 201                         for attr in file["attrs"]:
    202                                 if type(attr) is np.ndarray:
    203                                         delay_print(f"{attr: >{width}} {attr.dtype} {attr.shape}")

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/miniconda2/envs/jupyter/lib/python3.7/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    262                 raise ValueError("Invalid HDF5 object reference")
    263         else:
--> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    265 
    266         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'attrs' doesn't exist)"

**Comment by genomics-kl** [comment]
Update: I was able to read in the loom file using another conda environment that had loom v2.0.17. Thanks for the tip. I'll use this as a work-around until things work again.

**Comment by slinnarsson** [comment]
Updating to 3.0.5 should solve the problem! This was a bug specifically in 3.0.4.
