### ISSUE TITLE
Problem with the exon number feature on gtf file

### ISSUE THREAD

**Issue by SamueleSoraggi** [velocyto-team/velocyto.py#225]
Dear all,

I have been running the command `velocyto run` and used a gtf file which contains the exon number for only a part of the exons (it is a gtf where genes have been added). I get an error when velocyto start looking at those genes, and it is explicitely reported as an error message that the exon number is missing.
But I read in the manual that the exon number should be optional. Does the error pop up because I should remove all the exon numbers?

**Comment by SamueleSoraggi** [comment]
Solution found removing the exon name from the last column of the gtf file.

**Comment by st-tky** [comment]
I just wanted to share a solution other than removing the exon name from the column for someone else suffering from the same error.
This error can be solved also by adding exon name to the reporter gene that is going to be added manually.
The following is an example when you make a gtf file for reporter gene:
echo -e 'tdTomato\tunknown\texon\t1\t2084\t.\t+\t.\tgene_id "tdTomato"; transcript_id "tdTomato"; exon_number "1"; gene_name "tdTomato"; gene_biotype "protein_coding";' >  tdTomato.gtf
