### ISSUE TITLE
Samtools issue

### ISSUE THREAD

**Issue by kaizen89** [velocyto-team/velocyto.py#240]
Hi,
My issue has already been discussed  #192 but the suggested solution did not work for me.
I installed velocyto using the recommended installation.
Then samtools was not recognized as properly installed so I had to install it manually.
Next I ran this on on my laptop with 32 Gb RAM.
```
Path=~/Desktop/lab/bioinfo/projects/lung/
/home/abbas/anaconda3/bin/velocyto run -b $Path/cell_ranger_data/714ST/filtered_feature_bc_matrix_barcodes.tsv --samtools-memory 1950 -@ 14 -o $Path/Velocyto/714T/ $Path/cell_ranger_data/714ST/possorted_genome_bam714T.bam ~/Bash_downloads/refdata-cellranger-GRCh38-1.2.0/genes/genes.gtf
```
Samtools seem to work normally but then at the end I get this  message.
```
Traceback (most recent call last):
  File "/home/abbas/anaconda3/bin/velocyto", line 10, in <module>
    sys.exit(cli())
  File "/home/abbas/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/abbas/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/abbas/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abbas/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abbas/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/abbas/anaconda3/lib/python3.7/site-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/home/abbas/anaconda3/lib/python3.7/site-packages/velocyto/commands/_run.py", line 225, in _run
    Otherwise sort manually by samtools ``sort -l [compression] -m [mb_to_use]M -t [tagname] -O BAM -@ [threads_to_use] -o cellsorted_[bamfile] [bamfile]``")
MemoryError: bam file #0 could not be sorted by cells.
                This is probably related to an old version of samtools, please install samtools >= 1.6.                In alternative this could be a memory error, try to set the --samtools_memory option to a value compatible with your system.    
```
I also tried to first sort the bam file by cells but this doesn't change anything.
Any suggestions?

**Comment by kaizen89** [comment]
I changed a few things and finally it works, don't know what was causing the error.

**Comment by MalteMederacke** [comment]
What did you change, Ive got the same error

**Comment by kaizen89** [comment]
@MalteMederacke can you paste your command?

**Comment by MalteMederacke** [comment]
@kaizen89 Hi,

I tried to use 

velocyto run10x Nv24hpf/ genes.gtf 

were  Nv24hpf is the output of cellranger and genes.gtf the annotation file used for star. But acutally, I reinstalled the package and now it seemed to work. Can you still explain, what potentially went wrong at the first try?

**Comment by dKlee99** [comment]
@kaizen89 
hi, I'm also struggling with the same issue. 
`velocyto run -b /mnt/gmi-l1/_90.User_Data/woochan/Project/COVID-19/cellranger/Chromium038/outs/filtered_feature_bc_matrix/barcodes.tsv -o /gmi-l1/_90.User_Data/dlekrud456/velocyto/038 /mnt/gmi-l1/_90.User_Data/woochan/Project/COVID-19/cellranger/Chromium038/outs/possorted_genome_bam.bam /gmi-l1/_90.User_Data/dlekrud456/ref/refdata-gex-GRCh38-2020-A/genes/genes.gtf --samtools-memory 240000` is the command I used.  `MemoryError: bam file #0 could not be sorted by cells.
                This is probably related to an old version of samtools, please install samtools >= 1.6.                In alternative this could be a memory error, try to set the --samtools_memory option to a value compatible with your system.                 Otherwise sort manually by samtools ``sort -l [compression] -m [mb_to_use]M -t [tagname] -O BAM -@ [threads_to_use] -o cellsorted_[bamfile] [bamfile]``` is the error message I got. I'm not sure what was causing the error.

**Comment by saumyapo** [comment]
@dKlee99 I have the same error. Were you able to figure out a solution?
