### ISSUE TITLE
Can not locate the barcodes.tsv file

### ISSUE THREAD

**Issue by grimwoo** [velocyto-team/velocyto.py#246]
I just installed velocyto, and want to run ```velocyto run10x -m repeat_msk.gtf mypath/sample01 somepath/refdata-cellranger-mm10-1.2.0/genes/genes.gtf``` according to [tutorial](http://velocyto.org/velocyto.py/tutorial/cli.html).

My code is ```velocyto run10x /Cell_Ranger_Processed_Data/GTE001/out/filtered_feature_bc_matrix /Cell_Ranger/opt/refdata-cellranger-hg19-3.0.0/genes/genes.gtf```

However, I got the error: 
```
2020-02-26 13:10:05,451 - ERROR - This is an older version of cellranger, cannot check if the output are ready, make sure of this yourself
2020-02-26 13:10:05,451 - ERROR - Can not locate the barcodes.tsv file!
Traceback (most recent call last):
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 91, in run10x
    bcfile = bcmatches[0]
IndexError: list index out of range
```

I updated Cellranger to the latest version (3.0.2 -> 3.1.0). And I unzip the ".gz" file. However, I got the same error. Should I run Cellranger one more time to get a new "out" file? Or any other solutions?

**Comment by grimwoo** [comment]
And I tried using files ('.tsv.gz' or '.tsv') exported from seurat by 
```
library(DropletUtils)
library(Seurat)

setwd("D:/personal data/")
Patient.object <- readRDS...

write10xCounts(x = Patient.object@assays$RNA@counts, version="3", path = "D:/personal data/3")
write10xCounts(x = Patient.object@assays$RNA@counts, version="2", path = "D:/personal data/2")
```

And I got the same error information.

**Comment by SiyiWanggou** [comment]
Try
velocyto run10x /Cell_Ranger_Processed_Data/GTE001 /Cell_Ranger/opt/refdata-cellranger-hg19-3.0.0/genes/genes.gtf

**Comment by grimwoo** [comment]
Thanks. Using the output of higher version of CellRanger, I successfully ran Velocyto~

**Comment by ggruenhagen3** [comment]
For me the problem was I provided a subdirectory of the directory velocyto was expecting. velocyto expects samplefolder to be the one that contains 'outs/filtered_feature_bc_matrix/barcodes.tsv.gz'. Also it only worked for me when barcodes.tsv.gz was zipped.

**Comment by amasden** [comment]
> Thanks. Using the output of higher version of CellRanger, I successfully ran Velocyto~

Hello, could I ask how to avoid error below:
ERROR - This is an older version of cellranger, cannot check if the output are ready, make sure of this yourself

Thank you!

**Comment by denvercal1234GitHub** [comment]
@amasden - Did you resolve your issues? If so, would you mind posting the solutions plz?

**Comment by shaniAmare** [comment]
Hi, @denvercal1234GitHub ,

Barging in here, as I faced the same problem. The issue is that the `cellranger` output is too old for `velocyte` to understand. So I managed to send my data through the the traditional `velocyte` approach (i.e. `velocyto run`). An example is below.

```python
velocyto run \
    --bcfile /velocyte/C2Routput/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \ # filtered barcode file in gzipped format
    --outputfolder /velocyte/C2Routput \ # location for the output to go
    --samtools-threads 18 \ # optional, doesn't increase the speed much
    --samtools-memory 8000 \ # optional, doesn't increase the speed much
    -vvv \ # highest verbosity so I can debug if needed
    /velocyte/C2Routput/outs/possorted_genome_bam.bam \ # BAM file path
    /velocyte/mm10-transgene-premrna/genes/genes.gtf  # GTF file path - GTF file that was used for creating the cell ranger output
```
HTH,
Shani.

**Comment by GLking123** [comment]
> Hi, @denvercal1234GitHub ,
> 
> Barging in here, as I faced the same problem. The issue is that the `cellranger` output is too old for `velocyte` to understand. So I managed to send my data through the the traditional `velocyte` approach (i.e. `velocyto run`). An example is below.
> 
> ```python
> velocyto run \
>     --bcfile /velocyte/C2Routput/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \ # filtered barcode file in gzipped format
>     --outputfolder /velocyte/C2Routput \ # location for the output to go
>     --samtools-threads 18 \ # optional, doesn't increase the speed much
>     --samtools-memory 8000 \ # optional, doesn't increase the speed much
>     -vvv \ # highest verbosity so I can debug if needed
>     /velocyte/C2Routput/outs/possorted_genome_bam.bam \ # BAM file path
>     /velocyte/mm10-transgene-premrna/genes/genes.gtf  # GTF file path - GTF file that was used for creating the cell ranger output
> ```
> 
> HTH, Shani.

Thank you, you've given me a lot of help
