### ISSUE TITLE
pip install fails in MacOS Catalina 10.15.4

### ISSUE THREAD

**Issue by Sumithrasank** [velocyto-team/velocyto.py#254]
I tried installing with pip install velocyto and I get the error 
clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1
Please let me know of a solution. Thanks

**Comment by Mevelo** [comment]
Try `conda install -c conda-forge gcc libgcc llvm cython`

**Comment by Sumithrasank** [comment]
Thanks, I found this solution in an earlier issue and could install it
