### ISSUE TITLE
default_filter_and_norm index out of bounds

### ISSUE THREAD

**Issue by erinhwilson** [velocyto-team/velocyto.py#29]
Hello! Thanks again for your help with the interval file. I was able to use it to create a .loom file for a practice version of our dataset and now I'm working through the analysis pipeline tutorial.

One of the ways to get started mentions using `vlm.default_filter_and_norm()`. When I run that, I appear to get an index out of bounds error. I think might have to do with the `score_detection_levels()` function reducing the number of genes from ~60,000 to 441 but then the `score_cv_vs_mean()` function is still trying to use more than 441 genes...? But perhaps it's for another reason, not sure. 

Would this just mean that you have to experiment with providing inputs to the `vlm.default_filter_and_norm()` function or do you expect that the default function should have worked here? 

Here's the traceback:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-66-9ec18bcc69cb> in <module>()
----> 1 vlm.default_filter_and_norm()

~/ebs/workspace/velocyto.py/velocyto/analysis.py in default_filter_and_norm(self, min_expr_counts, min_cells_express, N, min_avg_U, min_avg_S)
   1587         self.filter_genes(by_detection_levels=True)
   1588 
-> 1589         self.score_cv_vs_mean(N=N, max_expr_avg=40)
   1590         self.filter_genes(by_cv_vs_mean=True)
   1591 

~/ebs/workspace/velocyto.py/velocyto/analysis.py in score_cv_vs_mean(self, N, min_expr_cells, max_expr_avg, svr_gamma, winsorize, winsor_perc, plot)
    274         ff = fitted_fun(log_m[:, None])
    275         score = log_cv - ff
--> 276         nth_score = np.sort(score)[::-1][N]
    277         if plot:
    278             scatter_viz(log_m[score > nth_score], log_cv[score > nth_score], s=3, alpha=0.4, c="tab:red")

IndexError: index 1000 is out of bounds for axis 0 with size 441
```

**Comment by gioelelm** [comment]
Hi and thank you again for the interest in ``veloctyo``

As I mention in issue #21 

> Also the methods starting with "defaults" are kind of macros. They logically pack a set of methods calls using some heuristic as arguments and are more intended as a reference then a facility. The idea is that users can look at the source code and try to adapt the steps to their pipeline. I should be more clear about it in the tutorial.

So for the default method I suggest inspecting the source and play with the parameter of each line. (I have to make this more clear in the docs) The thresholds that I am using are reasonable for standard 10X data.

Also it is suspicious to me that you are working with 60.000 genes... With human gene annotation you should get much less. Which kind of annotation files are you doing exactly? With the current version of ``velocyto`` you should be working using gene models not transcript models.

Right now you should consider ``velocyto`` as an alpha release. If you experiment feeding to it kind of analyses it was not tested on you might end up with weird errors: e.g. at this point we haven't thought about predicting typical user's incorrect usage and catched/raised the appropriate errors before they affect the output. 

To help you I think I will need some more info on what exactly you are running.
Is it 10X data? 
How many cells are you trying to analyze?
Which fraction of unspliced you get?
Have you tried to run with the .gtf provided by cellranger? Do you get different results?

**Comment by erinhwilson** [comment]
Ok, thanks for the clarification. I'll think of the default methods as a starting point and experiment some more with parameters to see if I can get them to work for this particular dataset!

We are using [this](http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/) human gtf file from ENSEMBL. A labmate mentioned that it may have some non-protein coding annotations in it which may explain the 60,000 genes. Do you think this would potentially cause problems using with Velocyto?

To your other questions: it is **not** 10x data and I haven't yet tried with a cellranger gtf file but I can give it a shot if you suspect cellranger's gtf would yield better results? Right now, I'm just trying to load a small subset of the data as I'm getting the hang of the package so for now its only about 420 cells but the idea would be to eventually apply it to the whole dataset which I believe is closer to 10,000. For the initial data I was able to load into a VelocytoLoom object, I got the following spliced to unspliced fractions: 
![plot_fractions](https://user-images.githubusercontent.com/33738960/33570188-deb95128-d8e0-11e7-9ee9-f6734fcf8c3b.png)


The unspliced/spliced ratio (~0.1) seems a little low relative to your Supplementary Fig 6C examples (between ~0.1 - 0.4) but maybe that's close enough?

**Comment by gioelelm** [comment]
Closed for inactivity,  feel free to reopen if necessary
