### ISSUE TITLE
MemoryError: Unable to allocate 6.16 MiB for an array with shape (32285, 100) and data type uint16

### ISSUE THREAD

**Issue by RosaKCL** [velocyto-team/velocyto.py#307]
Hi,
I keep running into a memory problem and the process gets killed while generating the loom file with velocyto run. I have tried sorting the bam file separately with samtools and running velocyto with different python versions and in different computers.  Could you please help me shedding some light into what the issue could be? The error I am getting is:

MemoryError: Unable to allocate 6.16 MiB for an array with shape (32285, 100) and data type uint16

I have attached the output and the error files from the HPC.

Thank you very much for your help!

[velocytoerror.txt](https://github.com/velocyto-team/velocyto.py/files/6492916/velocytoerror.txt)
[velocytooutput.txt](https://github.com/velocyto-team/velocyto.py/files/6492917/velocytooutput.txt)

**Comment by hartlama** [comment]
Also having this issue, even when running on a computing server with 500GB.

**Comment by wbvguo** [comment]
Also having this problem
