### ISSUE TITLE
multi10x output path

### ISSUE THREAD

**Issue by topherconley** [velocyto-team/velocyto.py#31]
Hi, 

Not sure where the `.loom` output file is located after running the following: 

```
$velo multi10x -n 4 -l $log_folder -m $repmask $parentfolder $intervals
```

All I see in STDOUT is this: 

> 2017-12-02 04:00:24,912 - DEBUG - Attempting to start 4 processes

Then I ran velocyto on each sample individually as a background process: 

```
for sample_path in $parentfolder/*;
do
  echo $sample_path 
  sample=`basename $sample_path`
  $velo run10x -m $repmask $sample_path $intervals 1> logs_velocyto/${sample}.log 2> logs_velocyto/${sample}.err &
done
```

It seems to be running each sample in the background well enough right now: 

> 2017-12-04 10:03:41,978 - DEBUG - Read first 100 million mapped reads
2017-12-04 10:05:21,292 - DEBUG - Marking up chromosome 17
2017-12-04 10:06:25,369 - DEBUG - Read first 110 million mapped reads
2017-12-04 10:08:30,929 - DEBUG - Marking up chromosome 18

Thus far I see a `velocyto/` folder in the `$sample_path`, 

**Where is the output going to be?** Perhaps make this more explicit in the documentation. 

**Any comments on the "multi10x" subcommand?**

**Comment by topherconley** [comment]
The `velocyto run10x` command worked in just about 2.5 hours per sample as suggested and put the output in `velocyto/sample_id.loom`. This is reported in the log at the end of completion. 

> 2017-12-04 11:46:06,268 - DEBUG - Generating output file $sample_path/velocyto/14737X3_mRNA.loom

Glad it worked! It would be helpful to explain the velocyto subfolder output to the user in the docs.

**Comment by gioelelm** [comment]
Thanks for the suggestions I will add some info to the docs about the velocyto subfolder. I was also thinking to maybe remove the command `multi10x`, as you probably figure out is just a shortcut that uses python `subprocess` to run several instances of of run10x, it is basically equivalent to what you are doing with your bash script.

**Comment by topherconley** [comment]
No problem.
