### ISSUE TITLE
Velocyto run10x Syntax Error

### ISSUE THREAD

**Issue by AAA-3** [velocyto-team/velocyto.py#310]
Hello!

I am brand new to python and this is the first time I am using the coding language so please forgive me if I am missing something basic...

I am wanting to run velocyto to get spliced and unspliced outputs and am running into the same problem as #131 and do not know how to proceed:

```
import os
os.chdir("/home/ali/Dokumente/R Practise/Run with all 54000+ features/Velocity")
os.getcwd()

mask = "/home/ali/Dokumente/R Practise/Run with all 54000+ features/Velocity/mm10_repeat_msk.gtf"
ref = "/home/ali/Dokumente/R Practise/Run with all 54000+ features/Velocity/genes.gtf"

b2_HET = ("/home/ali/Dokumente/R Practise/E14_5_Auswertung/Rohdaten/SCS_Wittmann/Batch 2/Wittmann_2_Hetero")

import velocyto
velocyto run10x -m mask b2_HET ref

#-m is for the repeat mask file location
#mask is the shorthand for the repeat mask file
#then the cell ranger output folder (shorthand b2_HET)
#last is the gene annotation file provided with the cellranger pipeline - shorthand name is ref
```
You can see the screenshots below showing that the directories are correct:
![image](https://user-images.githubusercontent.com/68068335/126524405-cb52a8fc-5b7c-4540-9a2f-7b3c3de1a1e4.png)
![image](https://user-images.githubusercontent.com/68068335/126524495-7b86de87-749b-4b23-bfe5-047c98be4863.png)

and the outs folder has the necessary subfolders: 
![image](https://user-images.githubusercontent.com/68068335/126524640-b5e74bc8-c866-4380-bf68-b0d15d48de91.png)

Yet, when I try to run the code in accordance to the [instructions](http://velocyto.org/velocyto.py/tutorial/cli.html#run10x-run-on-10x-chromium-samples) I keep getting and Invalid Syntax error:
![image](https://user-images.githubusercontent.com/68068335/126524926-cabc9416-3e2c-409d-9368-b011a4115fec.png)

Anyone have any ideas on how to overcome this?

**Comment by AAA-3** [comment]
I even put all the required files into one directory and ran the code:
```

import os
os.chdir("/home/ali/Dokumente/R Practise/Run with all 54000+ features/Velocity/Python Codes/B2_HET")
os.getcwd()

import velocyto

velocyto run -b barcodes.tsv -o b2het_out -m mm10_repeat_msk.gtf possorted_genome_bam.bam genes.gtf
```
 where `barcodes.tsv` is the name of the barcode file, `mm10_repeat_msk.gtf` is the mask file, etc. all in the same folder:

![image](https://user-images.githubusercontent.com/68068335/126668683-59fd583e-0ce1-4590-bd23-addd2998a344.png)

**Comment by AAA-3** [comment]
Just an FYI for others:
I resolved this issue by copy pating my code directly into the terminal, using full addresses and not going through a script. Velocyto is now running for me and I am debugging my files/code.

**Comment by AlexandraVal** [comment]
Hi!

Did you create the  repeat masker file or downloaded it from UCSC website for example?

**Comment by AAA-3** [comment]
> Hi!
> 
> Did you create the repeat masker file or downloaded it from UCSC website for example?

downloaded it from the UCSC web

**Comment by AlexandraVal** [comment]
Thank youu! Also, can you tell me which table did you use, please? I get an error for most of them so maybe I am not selecting the right one.

**Comment by AAA-3** [comment]
Here are my notes:

Repeat Mask file source:
https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=611454127_NtvlaW6xBSIRYJEBI0iRDEWisITa&clade=mammal&org=Mouse&db=mm10&hgta_group=allTracks&hgta_track=rmsk&hgta_table=0&hgta_regionType=genome&position=chr12%3A56694976-56714605&hgta_outputType=primaryTable&hgta_outputType=gff&hgta_outFileName=mm10_rmsk.gtf

clade: Mammal
genome: Mouse
assembly: mm10
group: All Tracks
track: RepeatMasker

Define region of interest: 
region: genome

Output format: GTF

Output name:mm10_repeat_msk.gtf
file type returned: plain text

21 JULY 1517 Uhr

**Comment by AlexandraVal** [comment]
Thank you very much!
