### ISSUE TITLE
Is it the right genome annotation file for cellranger 10X human to use? Chromosome MT+/- and others not present in the annotation

### ISSUE THREAD

**Issue by denvercal1234GitHub** [velocyto-team/velocyto.py#319]
Hi there, 

Would anyone mind confirming which Option 1 or 2 is the right gtf to use for humans run10x? Because when I ran velocyto for 10x, the .out file had 2 warnings as shown.

Thank you so much!

<img width="1130" alt="Screen Shot 2021-11-15 at 5 22 14 PM" src="https://user-images.githubusercontent.com/62179082/141826078-e2914ac1-5e45-408b-acb8-ce177372a3a6.png">

Option 1 (produced current error): I downloaded the gtf from: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/gencode.v32.primary_assembly.annotation.gtf.gz

Option 2: will I need to download "wget https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz" then, use the "genes.gtf" that is located in the refdata-gex-GRCh38-2020-A/genes directory

I downloaded expressed repeats annotation from (group = All tracks; track = RepeatMasker): https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=611454127_NtvlaW6xBSIRYJEBI0iRDEWisITa&clade=mammal&org=Human&db=0&hgta_group=allTracks&hgta_track=rmsk&hgta_table=rmsk&hgta_regionType=genome&position=&hgta_outputType=gff&hgta_outFileName=mm10_rmsk.gtf 

Releated issues: #315

**Comment by denvercal1234GitHub** [comment]
Solved. I will need to download "wget https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz" then, use the "genes.gtf" that is located in the refdata-gex-GRCh38-2020-A/genes directory

**Comment by hyjforesight** [comment]
I solved it. check this. https://github.com/velocyto-team/velocyto.py/issues/318

**Comment by denvercal1234GitHub** [comment]
Solved this. It is option 2. But encountering another issue #321 "Could not retrieve index file for the cellsorted_possorted_genome_bam.bam" even when the loom was successfully generated.

**Comment by AY-LIANG** [comment]
Hi,
I still get similar warning with option 2.
Any suggestions?

**Comment by denvercal1234GitHub** [comment]
@AY-LIANG -- Maybe it is just a warning and not necessarily an error?
