### ISSUE TITLE
normalize_by_total() fails after filter_cells() (update self.initial_cell_size)

### ISSUE THREAD

**Issue by bobermayer** [velocyto-team/velocyto.py#37]
when filtering cells using `vlm.filter_cells(totals > 500)`, only `vlm.S` and `vlm.U` get updated (resized), but `vlm.initial_cell_size` and `vlm.initial_Ucell_size` keep their original shapes. this leads to a 

ValueError: operands could not be broadcast together with shapes (ncells_before,) (ngenes, ncells_after) 

when calling `vlm.normalize_by_total()`

using `vlm.initial_cell_size=vlm.initial_cell_size[(totals > 500)]` fixes this problem

**Comment by gioelelm** [comment]
Thank you for reporting! This is fixed in the new version `0.12.2`, that I released just now. You don't need anymore the temporary fix ``vlm.initial_cell_size=vlm.initial_cell_size[(totals > 500)]``.
