### ISSUE TITLE
Running velocyto on 10x Cell Ranger cloud-generated files

### ISSUE THREAD

**Issue by schroeme** [velocyto-team/velocyto.py#371]
Hello, I am trying to run velocyto via the CLI on files generated from 10x Cell Ranger cloud analysis platform. This outputs filtered/raw count matrices as .h5 files, genome-aligned BAM and BAM index files, per-molecule read information .h5 file, etc. in the web browser which can then be downloaded. It seems based on [this documentation](https://velocyto.org/velocyto.py/tutorial/cli.html) that running velocyto on 10x Chromium samples requires the folder structure that results from `cellranger count`. Is this the case, or are just .bam files required? Can you elaborate on the directory structure and file types needed to run velocyto on 10x samples via CLI?

**Comment by zqzneptune** [comment]
Hi, 

Those files should be sufficient for running velocyto.

I am pasting command line, which worked on my side for your information:

`velocyto run -b /PATH TO TENX OUTPUT/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -o /PATH TO VELOCYTO OUTPUT FOLDER -m repeats_repeatMasker_allTracks.gtf -@ 16 --samtools-memory 2048 /PATH TO TENX OUTPUT/outs/possorted_genome_bam.bam GENE_ANNOTATION.gtf`

Indeed, if you can refer to the detailed documentation [here](http://velocyto.org/velocyto.py/tutorial/cli.html#run-run-on-any-technique-advanced-use)

**Comment by schroeme** [comment]
Thanks for your response! I ran the following command on my machine (Linux, Intel i9-10900X 20-core CPU, 256Gb RAM):

`velocyto run -b barcodes.csv -o velocyto_out -@ 20 --samtools-memory 2048 possorted_genome_bam.bam cjac_genes.gtf`

and got the following error after about an hour of runtime:

`raise MemoryError(f"bam file #{k} could not be sorted by cells.\n\
MemoryError: bam file #0 could not be sorted by cells.
                This is probably related to an old version of samtools, please install samtools >= 1.6.                In alternative this could be a memory error, try to set the --samtools_memory option to a value compatible with your system.                 Otherwise sort manually by samtools ``sort -l [compression] -m [mb_to_use]M -t [tagname] -O BAM -@ [threads_to_use] -o cellsorted_[bamfile] [bamfile]```

samtools version in the conda environment is 1.5. Any idea what might be causing this error?

**Comment by zqzneptune** [comment]
samtools 1.5 is a bit too old, the error msg saying >=1.6 is required. 

Maybe, you can try upgrading samtools?
