### ISSUE TITLE
Run10x Error

### ISSUE THREAD

**Issue by dylanmr** [velocyto-team/velocyto.py#38]
Hi, 

Thanks for developing such an exciting piece of technology! I am currently trying to run the velocyto CLI to generate a .loom file. However, when I submit the run10x command I receive the following error: 

TypeError: run10x() missing 1 required positional argument: 'molrep'

However, according to the tutorial, molrep does not appear to be an option in the 10x command. If I try to use the molrep option as defined in the run command in the run10x command I receive this error:

Error: no such option: --molrep

If you have any suggestions on how to correct this issue it would be greatly appreciated.

**Comment by gioelelm** [comment]
Thank you for the kind words on our work and for reporting this annoying bug! The error is now fixed in 0.12.3. Please feel free to open another issue if you encounter any further trouble running velocyto.py.
