### ISSUE TITLE
`set_clusters` should use string type for cluster labels for hdf5 dump

### ISSUE THREAD

**Issue by bobermayer** [velocyto-team/velocyto.py#40]
Hi,
when setting clusters from an external data frame (eg., read Seurat output using pandas with `vlm.set_clusters(my_annotation.loc[vlm.ca['CellID'],'cell.type'])`), the dtype of vlm.cluster_labels is `'O'`, which cannot be dumped into hdf5 (`TypeError: Object dtype dtype('O') has no native HDF5 equivalent`).
using `vlm.cluster_labels=vlm.cluster_labels.astype(np.string_)` fixes this problem but creates byte strings which is maybe not optimal. some unicode compatibility problem?

great package by the way!

**Comment by gioelelm** [comment]
Thank for reporting the bug, it was a little rare use case, but I fixed anyways in v0.12.4

> great package by the way!

Thank you!

**Comment by yueqiw** [comment]
Hi,

I'm running into the same issue with `vlm.set_clusters()` using Scanpy output. The dtype of `vlm.cluster_labels` and `vlm.colorandum` (Hex color code) are `'<U2'` and `'<U7'`, and this causes error in `vlm.to_hdf5()`. 

The following code fixes the problem: 
```
if x.dtype.kind == 'U': x = x.astype(np.string_)
```
