### ISSUE TITLE
prepare_markov question

### ISSUE THREAD

**Issue by tmfs10** [velocyto-team/velocyto.py#41]
Hi,

The prepare_markov function has two required parameters  -- sigma_D and sigma_W. However I'm unclear on what parameters those correspond to in the manuscript. If I could have clarification on that, that would be much appreciated!

Thanks!

**Comment by gioelelm** [comment]
What those sigmas are is clearly stated in the paragraph "Diffusion start and end-point modeling"
I attach a screenshot below:


![image](https://user-images.githubusercontent.com/4210138/35186175-2823d3fc-fe10-11e7-962f-5b3465996991.png)
