### ISSUE TITLE
Problem with velocyto.py install

### ISSUE THREAD

**Issue by lincoln-harris** [velocyto-team/velocyto.py#43]
I'm seeing the following error message after running "pip install velocyto":

Collecting velocyto
  Using cached velocyto-0.13.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8iDgnS/velocyto/setup.py", line 14
        package_data: dict = {}
                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8iDgnS/velocyto/

I have all of the proper dependencies installed, on a Ubuntu16.04 machine, running conda 4.4.7. Any ideas whats going wrong?

**Comment by gioelelm** [comment]
You are trying to install velocyto with python2.7! velocyto is only compatible with python >3.6

**Comment by gioelelm** [comment]
Could you confirm that using python 3.6 solves the problem?
Thanks

**Comment by lincoln-harris** [comment]
Thanks for the reply. I'll retry today with python 3.6 and let you know how
it goes.
Lincoln Harris
