### ISSUE TITLE
velocyto successfully installed but crashing 

### ISSUE THREAD

**Issue by rosshandler** [velocyto-team/velocyto.py#52]
Dear velocyto team,

 I have installed velocyto and dependencies following the installation guide. However, the program crashes simply when doing velocyto --help. It is funny because I have succeeded in different computers but now I just don't know what the problem could be. Bellow is the error I am getting, it seems to be related to matplotlib.cm. Please let me know if you recognise this problem

velocyto --help
Traceback (most recent call last):
  File "/homes/iimaz/miniconda3/bin/velocyto", line 7, in <module>
    from velocyto.commands.velocyto import cli
  File "/homes/iimaz/miniconda3/lib/python3.6/site-packages/velocyto/__init__.py", line 15, in <module>
    from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b, load_velocyto_hdf5
  File "/homes/iimaz/miniconda3/lib/python3.6/site-packages/velocyto/analysis.py", line 1936, in <module>
    colors20 = np.vstack((plt.cm.Vega20b(np.linspace(0., 1, 20))[::2], plt.cm.Vega20c(np.linspace(0, 1, 20))[1::2]))
AttributeError: module 'matplotlib.cm' has no attribute 'Vega20b'

Thank you!
Ivan

**Comment by slinnarsson** [comment]
Hi

Thanks for using velocyto!

Your error is probably related to different versions of matplotlib. I have 2.1.0 on my laptop, and it has `plt.cm.Vega20`, but that colormap seems to be missing (at least in the docs) in 2.2.0. The Vega colormaps were deprecated at some point in favor of `tabXX` colormaps. See https://github.com/ejeschke/ginga/issues/553

@gioelelm can probably fix it easily in the next release. For now, if you installed from source you can replace any occurrence of "VegaXXX" with the corresponding "tabXXX", e.g. Vega20b becomes tab20b. Alternatively, downgrading to matplotlib 2.1.0 should fix it.

**Comment by rosshandler** [comment]
Thank you. I used the second alternative.

pip uninstall matplotlib && pip install matplotlib==2.1.0

Awesome tool
