### ISSUE TITLE
Symbol not found: _GOMP_parallel

### ISSUE THREAD

**Issue by lmurrow** [velocyto-team/velocyto.py#53]
Hello, I am relatively new to python. Sorry if I am missing any information.

Velocyto installation completed, but when running `velocyto --help` to test installation I receive the following error:

```
$ velocyto --help
Traceback (most recent call last):
  File "/anaconda3/bin/velocyto", line 7, in <module>
    from velocyto.commands.velocyto import cli
  File "/anaconda3/lib/python3.6/site-packages/velocyto/__init__.py", line 13, in <module>
    from .estimation import fit_slope, _fit1_slope, clusters_stats
  File "/anaconda3/lib/python3.6/site-packages/velocyto/estimation.py", line 7, in <module>
    from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/velocyto/speedboosted.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /anaconda3/lib/python3.6/site-packages/velocyto/speedboosted.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda3/lib/python3.6/site-packages/velocyto/speedboosted.cpython-36m-darwin.so
```

I think this likely has something to do with my gcc version, but I'm not sure how to fix the problem.

```
$ python -V
Python 3.6.3 :: Anaconda custom (64-bit)
$ which gcc
/anaconda3/bin/gcc
$ gcc --version
gcc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by gioelelm** [comment]
Please install according to the instructions (using conda). Currently the
problem is that the compilation step was performed with a compiler not
supporting openmp. But this should not happen using the gcc version
provided by conda.

**Comment by lmurrow** [comment]
Thanks for responding so quickly. Sorry but I am confused. I did use conda to install all dependencies (as in the instructions), but used pip to install velocyto. I don't see any version of the velocyto package that is available to install using conda.

**Comment by gioelelm** [comment]
Is this solved?
If not, try  `conda install llvm`, ``conda install gcc`` or ``conda install libgcc``.
If this also does not work, try adding `-c conda-forge` I am pretty sure the version of the compiler provided by conda forge supports openmp.

**Comment by gioelelm** [comment]
Finally, if this does not work as well I had prepared a hacky solution for this occurrence.
- Unistall the current version.
- Get the source code cloning the repo.
- Change the `setup.py` script setting C_COMPILE = False
- Run `pip install -e . `

**Comment by lmurrow** [comment]
Thank you, the first option worked! Will close this out.

**Comment by Julie-UM** [comment]
> Is this solved? If not, try `conda install llvm`, `conda install gcc` or `conda install libgcc`. If this also does not work, try adding `-c conda-forge` I am pretty sure the version of the compiler provided by conda forge supports openmp.

Hi, when I use conda to RUN velocyto in macbook pro, it retruns such problem. Can you have any ideas to resolve it? Many thanks! #
![WechatIMG15](https://user-images.githubusercontent.com/103257844/162438606-614778fe-f52f-41f0-bc5d-57f4c5e5f69d.jpeg)

**Comment by Julie-UM** [comment]
Hi, when I use conda to RUN velocyto in terminal of macbook pro, it retruns such problem. Do you have any ideas to resolve it? Many thanks! 

> Is this solved? If not, try `conda install llvm`, `conda install gcc` or `conda install libgcc`. If this also does not work, try adding `-c conda-forge` I am pretty sure the version of the compiler provided by conda forge supports openmp.

Hi, when I use conda to RUN velocyto in terminal of macbook pro, it retruns such problem.Do
![Uploading WechatIMG15.jpeg…]()
 you have any ideas to resolve it? Many thanks!

**Comment by Julie-UM** [comment]
> Is this solved? If not, try `conda install llvm`, `conda install gcc` or `conda install libgcc`. If this also does not work, try adding `-c conda-forge` I am pretty sure the version of the compiler provided by conda forge supports openmp.

Hi, when I use conda to RUN velocyto in terminal of macbook pro, it retruns such problem. Do you have any ideas to resolve it? Many thanks! I had tried The methods you mentioned above, but is not suitable for my problem.
![WechatIMG15](https://user-images.githubusercontent.com/103257844/162439609-90e4101b-5aad-41f2-8927-784ffd626a0b.jpeg)
