### ISSUE TITLE
Where would we expect the executable `velocyto --help`? 

### ISSUE THREAD

**Issue by evanbiederstedt** [velocyto-team/velocyto.py#55]
Following the instructions, I've been able to (seemingly sucessfully) install velocyto via `pip` and installing from source via github, i.e.

```
git clone https://github.com/velocyto-team/velocyto.py.git
cd velocyto.py
pip install -e .  # note the trailing dot
```

outputs

```
Installing collected packages: velocyto                                                                                                                                          
  Found existing installation: velocyto 0.13.8                                                                                                                                   
    Uninstalling velocyto-0.13.8:                                                                                                                                                
      Successfully uninstalled velocyto-0.13.8                                                                                                                                   
  Running setup.py develop for velocyto                                                                                                                                          
Successfully installed velocyto
```

However, I cannot find the executable 

```
$ velocyto --help
bash: velocyto: command not found 
```

As I'm using multiple versions of Python, this isn't set-up as the "default" python. Where is this executable?

**Comment by gioelelm** [comment]
This depends on which pip executable you are using (try `which pip`). 
Usually the installation should make it available to your path, so it is a bit weird it is not happening here. Maybe try to install without the `-e`.

If still does not work I strongly encourage you to use a conda environment, activating the environment you will be sure to have the velocyto command available.

**Comment by evanbiederstedt** [comment]
> This depends on which pip executable you are using (try which pip).

Given the path of `which pip`, where should the executable be placed? 

> Usually the installation should make it available to your path

Could you give details about this? 

I'll try again without an `-e`

**Comment by gioelelm** [comment]
> Given the path of which pip, where should the executable be placed?

In the same folder: for example for `~/anaconda3/bin/pip` is `~/anaconda3/bin/velocyto`

> Could you give details about this?

I am setting an entry point using `click` library default options, I am not sure exactly what `click` does in the background.

**Comment by evanbiederstedt** [comment]
You're right. I installed with `pip3` in `Python-3.6.3/bin/` i.e. `~/python-###/bin/pip3`, so the `velocyto` executable is located `~/python-###/bin/velocyto`. 

It does work:

```
Usage: velocyto [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  run     Runs the velocity analysis outputing a loom file
  run10x  Runs the velocity analysis for a Chromium Sample
```
