### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by harmbrugge** [velocyto-team/velocyto.py#58]
I'm trying to install velocyto on macos High Sierra using conda 4.5.0 python version Python 3.6.5.
All the dependencies install fine but `pip install velocyto` yields the following error:

```
Building wheels for collected packages: velocyto
  Running setup.py bdist_wheel for velocyto ... error
...
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/harmbrugge/anaconda3/envs/3point6/include -arch x86_64 -I/Users/harmbrugge/anaconda3/envs/3point6/include -arch x86_64 -I/Users/harmbrugge/anaconda3/envs/3point6/lib/python3.6/site-packages/numpy/core/include -I/Users/harmbrugge/anaconda3/envs/3point6/include/python3.6m -c velocyto/speedboosted.c -o build/temp.macosx-10.7-x86_64-3.6/velocyto/speedboosted.o -fopenmp -ffast-math
  clang: error: unsupported option '-fopenmp'
  error: command 'gcc' failed with exit status 1
```
I think the problem is that i'm using an old gcc version and tried installing the latest version using homebrew: `brew install cmake gcc`, but I'm not sure how to link the new gcc instalation with pip

**Comment by gioelelm** [comment]
Thank you for the interest in our software and for reporting the problem.

In this case solution could be found in the closed issues session, I admit that I often forget to check it myself, but it is a usefull thing to do :) 

Se here: https://github.com/velocyto-team/velocyto.py/issues/53

**Comment by harmbrugge** [comment]
Thank you for your swift response. `conda install gcc` did the trick.

I did run into another issue: `fatal error: limits.h: No such file or directory`. I solved this by running `xcode-select --install` which apparently will install system headers into standard locations expected by tools like gcc.
