### ISSUE TITLE
Issue with IndexError when running smartseq2 bam files

### ISSUE THREAD

**Issue by lushjia** [velocyto-team/velocyto.py#64]
Hi,  
I was using velocyto run_smartseq2 command to run some bam files. Most of them work well, but some bam files will get back "**IndexError: list index out of range**" this error when reading the bam (after summarizing the results of intron validation). It seems like this:
![_20180418212525](https://user-images.githubusercontent.com/38059727/38935236-6ff38030-4350-11e8-9c28-e6a9cdb5f56a.jpg)
We used GSNAP for RNAseq alignment, maybe there are some special cigar. For example, we think this kind of reads (below) will cause the error but are not very sure and don't know why. Is there some easy ways to find which reads are not satisfied the requirement and how to deal with them? 
![_20180418213104](https://user-images.githubusercontent.com/38059727/38935177-42175a10-4350-11e8-9b96-0dd64848d784.png)
Thank you very much!

**Comment by gioelelm** [comment]
Ok I see the problem the aligner is report insertion + deletion instead of missmatch. Weird but I guess it depends from the parameters. I will fix

**Comment by gioelelm** [comment]
The problem should be now fixed in version 0.17.2

Thank you a lot for reporting spotting exactly the line of the bam that was causing trouble!
