### ISSUE TITLE
Issue with AttributeError when running smartseq2 bam files

### ISSUE THREAD

**Issue by lushjia** [velocyto-team/velocyto.py#66]
Sorry for disturbing you again, but after you fixed the former problem, I get a new one.
Also when using velocyto run_smartseq2 command to run bam files, I get the error “**AttributeError: 'list' object has no attribute 'add'**”. It likes this:
![_20180419110947](https://user-images.githubusercontent.com/38059727/38969313-3472e894-43c2-11e8-9a4e-e125bf5b3ccc.jpg)
It seems to happen where you fix your code yesterday. Here is the link (below) of two of my samples which will get this error, if you would like to try to run them using smartseq2 logic.
https://1drv.ms/f/s!Ah6kTQEKGo66giSsQqtqeLOF8j8c
Thank you very much for making the software and helping us solve the problems.

**Comment by gioelelm** [comment]
Ok you are right sorry, I tested the solution but ultimately forgot to change a line .
Should be solved in 0.17.3
