### ISSUE TITLE
Typo in gene_knn_imputation

### ISSUE THREAD

**Issue by karlann** [velocyto-team/velocyto.py#67]
Hey!
There's a typo in the analysis.py gene_knn_imputation function.
On line 1107 it's currently `connectivity = (self.knn > 0).atype(float)`
But it should be with `connectivity = (self.knn > 0).astype(float)`

**Comment by gioelelm** [comment]
I will fix but that function will be deprecated

**Comment by gioelelm** [comment]
fixed
