### ISSUE TITLE
vlm.normalize_median

### ISSUE THREAD

**Issue by cds1** [velocyto-team/velocyto.py#71]
Dear velocyto team, 
I am currently following your tutorial online to learn how to work with velocyto to then apply the same code to my data. Unfortunately, I cannot get passed the vlm.normalize_median() step in your script. Maybe it is something obvious so apologies in advanced if this is the case. I should say that I am not working in ipython due to a system and administration issues with all the dependencies. Instead I am submitting my script to a computer farm. I am also following exactly what is in your code. The only exception are the modules that I import which are almost the same except for the ipython/display import. 

import sys
import numpy as np
from scipy.stats import norm
from scipy.spatial.distance import pdist, squareform
import matplotlib
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
import loompy
import velocyto as vcy
import logging

So... the error I keep getting is the following:

Traceback (most recent call last):
  File "test.py", line 81, in <module>
    vlm.normalize_median()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/analysis.py", line 898, in normalize_median
    self.Sx_sz = self.Sx * (np.median(self.Sx.sum(0)) / self.Sx.sum(0))
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4119, in median
    overwrite_input=overwrite_input)
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4033, in _ureduce
    r = func(a, **kwargs)
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4152, in _median
    part = partition(a, kth, axis=axis)
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 664, in partition
    a.partition(kth, axis=axis, kind=kind, order=order)
ValueError: kth(=9106) out of bounds (1)

I am also attaching the script that I am running in case. 
I would be very greateful if you have any ideas of what the problem is.
Kind regards,
[test.txt](https://github.com/velocyto-team/velocyto.py/files/1991206/test.txt)

Carmen

**Comment by cds1** [comment]
Hello, 
Not at all! Thank you so much for letting me know. I will keep an eye on the update of the notebooks and in the meantime I will give the tutorial a try. 
It seems like a great tool and I loved the paper as well. 
Thanks, Carmen

**Comment by cds1** [comment]
Hello again
Would I need to re-install velocyto? I am asking because after changing the script as you can see in the new error, it does not let me to fit the gammas. 

File "test.py", line 78, in <module>
    vlm.fit_gammas()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/analysis.py", line 1198, in fit_gammas
    denom_Sx[denom_Sx == 0] = np.maximum(np.max(self.Sx[denom_Sx == 0, :], 1), 0.001)
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions

Thanks again

**Comment by gioelelm** [comment]
Nom I don't think so. The error is particularly weird.
Could you run before the error: 

```
np.percentile(self.Sx, 99.9, 1).shape
```

and paste here the results?

**Comment by cds1** [comment]
Hello, 
I ran:
...
vlm.perform_PCA()
vlm.knn_imputation(n_pca_dims=20, k=500, balanced=True, b_sight=3000, b_maxl=1500, n_jobs=16)
np.percentile(vlm.Sx, 99.9, 1).shape
vlm.fit_gammas()
...
 and got the same error:
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/analysis.py", line 1198, in fit_gammas
    denom_Sx[denom_Sx == 0] = np.maximum(np.max(self.Sx[denom_Sx == 0, :], 1), 0.001)
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions

**Comment by gioelelm** [comment]
Sorry I was not clear, I mean: could you print the result of 

```
np.percentile(vlm.Sx, 99.9, 1).shape
```

and maybe as well of of

```
vlm.S.shape
```

I recommend running in interactive more (e.g. jupyter or ipython) to get possible warnings and controlling the workflow better. Especially the first time

**Comment by cds1** [comment]
ok, sorry.. This is what i am running:
vlm.perform_PCA()
vlm.knn_imputation(n_pca_dims=20, k=500, balanced=True, b_sight=3000, b_maxl=1500)

print("---------")
print(vlm.S.shape)
print(np.percentile(vlm.Sx, 99.9, 1).shape)
vlm.fit_gammas()
Output:
---------
(3001, 18121)
(3001,)
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    vlm.fit_gammas()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/analysis.py", line 1198, in fit_gammas
    denom_Sx[denom_Sx == 0] = np.maximum(np.max(self.Sx[denom_Sx == 0, :], 1), 0.001)
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions

**Comment by gioelelm** [comment]
Ok, instead of investigating the causes deeper I just made the code more general. Now 0.17.7 should not crash anymore (or crash somewhere different).

Please let me know if the bug was fixed!

**Comment by gioelelm** [comment]
Also notebooks have been updated

**Comment by cds1** [comment]
Hello, Thanks for doing this. Actually I get exactly the same error. I have the feeling that something in our computer farm/system clashes with the scripts. I cannot test velocyto in my home directory because I do not have admin access and so it fails each time I need to install pysam with pip.  Installing pysam with conda is not an option because conda then tries to downgrade python to 2.7. It's all becomes really complicated. 
 I only managed to test velocyto using the docker for velocyto.R. This is a problem because I do not see an option to deal with 10X data in the R package. I may just ask that question in the velocyto R section... 

Cheers, Carmen

**Comment by gioelelm** [comment]
Is it the same if you reduce the size of the dataset. Let's say using filter cells function or loading a smaller loom file?

**Comment by cds1** [comment]
I didn't think it was a memory issue but I will try with the filter cell function that you mention.

**Comment by mschilli87** [comment]
@cds1:
> I do not have admin access and so it fails each time I need to install pysam with pip.

Have you tried the `--user` flag for `pip`?

**Comment by gioelelm** [comment]
> I didn't think it was a memory issue but I will try with the filter cell function that you mention.

Probably is not, I was only suspecting that some cells are so low that after filtering you get some division by zero. 


Also, are you really sure to be using the latest version and to have uninstalled all the previous version correctly (before I encountered a similar problem where I had somehow installed multiple version and I had to uninstall a couple of times before cleaning it up).

For example error should now say:

> File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/analysis.py", line **1199**, in fit_gammas
