### ISSUE TITLE
Installation Error "clang: error: unsupported option '-fopenmp'"

### ISSUE THREAD

**Issue by diazdc** [velocyto-team/velocyto.py#74]
Good day,

I'm trying to install the latest version via pip and I receive the following error after gcc:

`gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ddiaz/anaconda3/include -arch x86_64 -I/Users/ddiaz/anaconda3/include -arch x86_64 -I/Users/ddiaz/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/ddiaz/anaconda3/include/python3.6m -I/Users/ddiaz/anaconda3/include/python3.6m -c velocyto/speedboosted.c -o build/temp.macosx-10.7-x86_64-3.6/velocyto/speedboosted.o -fopenmp -ffast-math
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1`

I'm trying to install velocyto on macOS Sierra version 10.12.6. Thanks.

**Comment by gioelelm** [comment]
Thank you for the interest in our software.

Yours is a compiler issue, the solution of your problem can be found here: https://github.com/velocyto-team/velocyto.py/issues/53

**Comment by gioelelm** [comment]
solved?

**Comment by diazdc** [comment]
Sorry for the late reply. Thanks, I solved this using `condo install gcc.
