### ISSUE TITLE
Would you please provide the loom.file of mouse hippocampus as a reference?

### ISSUE THREAD

**Issue by sunyan4BGI** [velocyto-team/velocyto.py#75]
Hello,we got some troubles in analyse pipline,it is hard to understand each parameter.
Would you please provide the loom.file of mouse hippocampus as a reference?

**Comment by gioelelm** [comment]
The general tutorial can be found [here](http://velocyto.org/velocyto.py/tutorial/analysis.html), while analysis notebooks that one can use as examples are available [here](https://github.com/velocyto-team/velocyto-notebooks/tree/master/python). For detailed explanation on inputs parameters  in detail the related [section of the docs](http://velocyto.org/velocyto.py/fullapi/api_analysis.html). Furthermore, clicking on the ``[source]`` link, will show to the actual code of each function ito get more detailed info on the exact computations performed.

Reference loom file is already available at (the link could be already found looking at the example notebooks):
http://pklab.med.harvard.edu/velocyto/DentateGyrus/DentateGyrus.loom

**Comment by sunyan4BGI** [comment]
I'm so sorry I didn't find this, thank you for your patience.

**Comment by gioelelm** [comment]
No problem! Thanks for reporting that this was not clear, might be useful for other users when they Google for it.
