### ISSUE TITLE
Run out of memory error (10X pipeline)

### ISSUE THREAD

**Issue by Xabiermm1** [velocyto-team/velocyto.py#79]
Running 10X pipeline in command line:
I tried:
      1ª Samtools run outside the pipeline
      2ª Samtools run inside the pipeline
In two options I get the same output with no ".loom" file generated.

It looks like it's using python numpy concatenate function to relocate all the counts in memory and my ram it's not enough. 

My server has 64 GB of ram but it looks like the pipeline took about 100GB (36GB of swap memory), the problem is that this step cant work with swap and try to get all the 100GB in memory...

Is this the problem?, Could this function be changed to serialize or something and not loading all the counts in memory?

https://www.dropbox.com/home/singleCell_KAUST?preview=velocyto_Melanoma.odp#
https://www.dropbox.com/home/singleCell_KAUST?preview=velocyto_Melanoma.odp#

Thx
Xabi

**Comment by gioelelm** [comment]
I need the exact command you run and the log file to give a relevant answer

**Comment by Xabiermm1** [comment]
The command:
opt/python/bin/velocyto run10x -m /home/xabiermm1/repeat_gtf/human_repeat_msk.gtf /home/xabiermm1/A3 /home/xabiermm1/refdata/genes/genes.gtf

Log_Img:
![log](https://user-images.githubusercontent.com/9248410/40612414-b524960a-627a-11e8-8bc8-b4ee64b5a4f9.png)
err_Log_img:
![error_log](https://user-images.githubusercontent.com/9248410/40612417-b72f9c6a-627a-11e8-8bac-c768383e2cc6.png)

**Comment by Xabiermm1** [comment]
Solved.
Running in a server with 128GB works perfect.

Xabi

**Comment by ChelseaCHENX** [comment]
Hi Xabi,
I am having exactly the same problem - my memory requirement seems to be even larger than you... Just wonder how you calculate the requiring memory in this last step - I cannot see that in the error img from both yours or my file - would you mind helping? Thx!
