### ISSUE TITLE
When clustering cells from multi samples, are there some ways to remove batch effects?

### ISSUE THREAD

**Issue by sunyan4BGI** [velocyto-team/velocyto.py#83]
Hi, Gioelelm, I'm asking you again   : -)
When I clustered cells from multi samples using tSNE, I found obvious batch effects (after colored by samples).
I wounder if there are some ways to remove them.
Or if I labeled velocities on an existing tSNE plot from Seurat, is it still meaningful?
Because as I know, Seurat clusters cells according to all reads, however velocyto clusters cells only according to reads that mapped to spliced mRNAs?

**Comment by gioelelm** [comment]
I suggest to perform a feature selection and work with genes that are not strongly biassed in one or the other batch (there are several ways you might want to do this). Make sure that the batch effect disappears, at least in the first principal components, before applying velocyto otherwise the velocity estimate that you will get might be difficult to interpret correctly.

**Comment by sunyan4BGI** [comment]
Emmm.......Is there any way to perform feature selections in velocyto?
what if I don't perform a feature selection, but label velocities on an existing tSNE embedding that has removed batch effects?
Recently, there was an article published on Science, they calculated velocities of Flatworms' cells,and labeled them on an embedding given by Seurat.  
Here is the article: http://dx.doi.org/10.1126/science.aaq1723
Does is still make sense? Because the gene set used to calculate velocities is different from the one used to cluster (When clustering, some genes are filtered to avoid batch effects).

**Comment by gioelelm** [comment]
Yes feature selection is implemented. Use score_cv_vs_mean follow by
filter_genes by_cv_vs_mean = True

Yes it makew sense. You can calculate velocity with the set of genes that
you prefer, as soon as you describe what and why you are doing it

**Comment by sunyan4BGI** [comment]
OK,I get it.
Thanks for your answer!     :-）
