### ISSUE TITLE
smart-seq2 stranded

### ISSUE THREAD

**Issue by foehnwind** [velocyto-team/velocyto.py#84]
Hi Developers,

Below is an excerpt of logic `SmartSeq2`:
```py
class SmartSeq2(Logic):
    """SmartSeq2 logic
    """

    def __init__(self) -> None:
        self.name = "SmartSeq2"

    @property
    def layers(self) -> List[str]:  # This should be overridden if a different set of layers is desired
        return ["spliced", "unspliced", "ambiguous", "spanning"]

    @property
    def stranded(self) -> bool:
        return False
```
I wonder if it true that SmartSeq2 will treat reads as non-stranded, even for stranded data? Thanks.

**Comment by gioelelm** [comment]
Yes it will ignore the strand information.

**Comment by gioelelm** [comment]
The behaviour will depend on the output of preprocessing and alignment.
Velocyto considers each entry of the bam file as an independent mapping of
a read.

So if the bam file has two entries corresponding to R1 and R2 for each
illumina cluster, then yes they will be counted twice. If you would rather
have another behavior you can change the logic or the bam file itself.

**Comment by foehnwind** [comment]
Thanks to your answer. That explains my observation that, when I tried to feed velocyto a bam file with only R1 or R2, I got half number of counts as the entire bam file. 

This behavior seems unexpected to me, because mainstream paired-end quantification tools avoid such double counting scheme. Here is an example from HTSeq document (http://htseq.readthedocs.io/en/master/count.html):
> For paired-end data, does htseq-count count reads or read pairs?
>     Read pairs. The script is designed to count “units of evidence” for gene expression. If both mates map to the same gene, this still only shows that one cDNA fragment originated from that gene. Hence, it should be counted only once.

**Comment by gioelelm** [comment]
It is a very good point. Is there a standard of how/in which entry to encode this information in the bam file?

I am very happy to bring this in line with the standard in the field. I also think that using both reads jointly can help providing evidence for the existence of a longer fragment that could be more informative in the context calling of exon-intron or exon-exon spanning fragments.

If you have some time to talk about this more in detail and maybe help by checking a test implementation, please don't hesitate to contact me by email.

**Comment by foehnwind** [comment]
Thanks again for your confirmation. 

Sure. Bam file has read pair (among others) information encoded in "flag" (https://broadinstitute.github.io/picard/explain-flags.html): 0x40 indicates R1 and 0x80 R2. In terms of paired-end quantification logic, there are two widely used packages HTSeq (https://github.com/simon-anders/htseq/tree/master) and FeatureCount (http://subread.sourceforge.net/) you might refer to. Essentially, both package assigns a count to a gene, if one or both mates are aligned.
