### ISSUE TITLE
shape of feature selection and problems with vlm.perform_PCA() 

### ISSUE THREAD

**Issue by cynthiazhou1005** [velocyto-team/velocyto.py#87]
Hi, 

I'm trying to get a first look of the loom file. I have two questions:
1. the feature selection commands returned me a figure that doesn't look like what was shown in the notebook:
vlm.score_cv_vs_mean(3000, plot=True, max_expr_avg=35)
vlm.filter_genes(by_cv_vs_mean=True)
On my data, it returned a plot the opposite direction as shown on the notebook.
![image](https://user-images.githubusercontent.com/22435912/41748148-70f78a34-7565-11e8-87cb-f11270c673de.png)

2. Jupyter notebook i have seems not be able to run vlm.perform_PCA() command. Kernel killed. 
I used the standard command lines to import and do normalizations, but didn't have clusters imported yet. Is there something wrong with my data import? 

Thanks again for everything.

**Comment by gioelelm** [comment]
This is really peculiar, I am looking at the code and I have no clue on what can cause the misbehaviour on your machine.

Why don't you look at the source code of score_cv_vs_mean and try to run the code line by line (substitute self to vlm) in the notebook while inspecting the results?
Check the data matrices is there something strange?

**Comment by gioelelm** [comment]
Have you tried to run the example notebook of the Human or mouse data we
provide? Does that work?

**Comment by cynthiazhou1005** [comment]
I fixed that by running the analysis on the linux system, so I guess it was just the incompatibility for Mac for some reason!
One more quick question. I used the velocyto run command instead of run10x. Is there anyway I can append the attributes (clusters) to the loom file afterwards? 
I get this problem when I try to plot the arrows:

'VelocytoLoom' object has no attribute 'colorandum'


Thanks!

**Comment by cynthiazhou1005** [comment]
I got the plot to work by giving everything the same cluster attribute and run set_cluster. It's looking very promising. Now I just need to figure out how to plot in a meaningful way and the right cluster colors.Thank you so much for all the help and guidance! @gioelelm

**Comment by EularTang** [comment]
> @cynthiazhou1005 Could you tell me if you used Anaconda Python when you got the error, and if so, which version? See #104 .

I have the same problem , and I used Anaconda Python which version is Python 3.6.6.What should I do?
Thank you for your attention.
[scatter_dict = {"s": 20, "zorder": -1, "alpha": 0.2, "lw": 0, "c": self.colorandum}
AttributeError: 'VelocytoLoom' object has no attribute 'colorandum']

**Comment by gioelelm** [comment]
As specified in #104, this is a problem caused by anaconda's bugged `mkl`. You may consider installing a conda environment that uses the conda-forge channel, they do not depend `mkl` using `openblas` at the backend of their scipy stack, maybe it is enough to do the trick! 

This might do the trick 
```
conda config --add channels conda-forge
conda install numpy
```
(adding conda-forge can also cause conflicts to the working environment so I suggest to run these comands on a new conda environment)

**Comment by Sabermea** [comment]
@cynthiazhou1005 I have the same problem. Were you able to fix the issue you had?

**Comment by gioelelm** [comment]
> [scatter_dict = {"s": 20, "zorder": -1, "alpha": 0.2, "lw": 0, "c": self.colorandum}
AttributeError: 'VelocytoLoom' object has no attribute 'colorandum']

I think this error has really nothing to do with this thread.

Your error just means that the color for each pixel is not set, because the clusters have not been set.
Set cluster or set vlm.colorandum = "k" or a list of color in a format that matplotlib accepts to keep running the code.

**Comment by Sabermea** [comment]
Thanks @gioelelm! Could you please provide an example of how we could set the clusters?
If we should cluster the cells using a different tool, how we could integrate the clustering results.
Thank you in advance!

**Comment by gioelelm** [comment]
We have a full API guide on velocyto.org, don't esitate to check there for this kind of doubts! In particular when examples notebooks are not enough. You do it by:vlm.set_clusters(clusters)Where clusters needs to be dermined using some clustering algorithm using the vlm.S matrix after applying the usual pre-filtering and normalization steps.

**Comment by Sabermea** [comment]
Thank you very much @gioelelm!
