### ISSUE TITLE
Multi bam files and cell barcodes

### ISSUE THREAD

**Issue by vagnec** [velocyto-team/velocyto.py#89]
Hi,

I'm sorry because I think my question is very very naive...

I got an error while running velocyto:
logging.debug(f"Example of barcode: {valid_bcs_list[0]} and cell_id: {valid_cellid_list[0]}")

I don't understand what is wrong. I didn't add any cell barcode, as I have one bam file per cell. There is no barcode in the reads of my bam files.

Thank you in advance for your help

**Comment by gioelelm** [comment]
To be able to answer I need:
- Command that you run
- log or more complete traceback
- info in the installation (importantly are you using conda?)

**Comment by vagnec** [comment]
Hi Gioele,

- The command that I ran is: `"velocyto run --onefilepercell -o output bamfiles/*/*bam path/Mus_mu
sculus.GRCm38.90_UCSConlychr.gtf`
- To install velocyto, I used conda.
```
# packages in environment at /path_analyses/software/miniconda/envs/velocyto:
#
blas                      1.1                    openblas    conda-forge
ca-certificates           2017.11.5                     0    file://path_software/conda-package
certifi                   2018.4.16                py36_0    conda-forge
click                     6.7                        py_1    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.28.3           py36hfc679d8_0    conda-forge
dbus                      1.10.22                       0    file://path_software/conda-package
expat                     2.2.5                         0    file://path_software/conda-package
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.7                        1    file://path_software/conda-package
glib                      2.51.4                        0    file://path_software/conda-package
gst-plugins-base          1.8.0                         0    file://path_software/conda-package
gstreamer                 1.8.0                         2    file://path_software/conda-package
h5py                      2.8.0            py36hb794570_1    conda-forge
hdf5                      1.10.2                        0    conda-forge
icu                       58.2                          0    file://path_software/conda-package
jpeg                      9b                            2    file://path_software/conda-package
kiwisolver                1.0.1                    py36_1    conda-forge
libffi                    3.2.1                         3    file://path_software/conda-package
libgcc                    5.2.0                         0    file://path_software/conda-package
libgcc-ng                 7.2.0                hdf63c60_3
libgfortran               3.0.0                         1    file://path_software/conda-package
libgfortran-ng            7.2.0                hdf63c60_3
libiconv                  1.15                          0    file://path_software/conda-package
libpng                    1.6.34                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3
libxcb                    1.12                          1    file://path_software/conda-package
libxml2                   2.9.5                         0    file://path_software/conda-package
llvmlite                  0.23.0                   py36_1    conda-forge
loompy                    2.0.9                     <pip>
matplotlib                2.2.2                    py36_1    conda-forge
ncurses                   5.9                          10    file://path_software/conda-package
numba                     0.38.1                   py36_0    conda-forge
numpy                     1.14.5          py36_blas_openblashd3ea46f_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2n                        0    file://path_software/conda-package
pcre                      8.39                          0    file://path_software/conda-package
pip                       9.0.3                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_5    conda-forge
pysam                     0.14.1                    <pip>
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py36_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                39.2.0                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
typing                    3.6.4                     <pip>
velocyto                  0.17.8                    <pip>
wheel                     0.30.0                     py_1    file://path_software/conda-package
xorg-libxau               1.0.8                         3    file://path_software/conda-package
xorg-libxdmcp             1.1.2                         3    file://path_software/conda-package
xz                        5.2.3                         0    file://path_software/conda-package
zlib                      1.2.11               h470a237_3    conda-forge
```
- The log I got is: 
```
2018-07-05 14:12:54,959 - WARNING - Each bam file will be interpreted as a DIFFERENT cell
2018-07-05 14:12:54,970 - WARNING - When using mutliple files you may want to use --sampleid option to specify the name of the output file
2018-07-05 14:12:54,970 - INFO - No SAMPLEID specified, the sample will be called onefilepercell_LNMA01_and_others_CLH77 (last 5 digits are a random-id to avoid overwriting some other file by mistake)
2018-07-05 14:12:54,970 - DEBUG - Using logic: Default
2018-07-05 14:12:54,971 - DEBUG - Cell barcodes will be determined while reading the .bam file
2018-07-05 14:12:54,985 - WARNING - Your system does not support calling `grep MemAvailable /proc/meminfo` so the memory effort for the samtools command could not be chosen appropriatelly. 32Gb will be assumed
2018-07-05 14:12:54,986 - DEBUG - The multi input option
2018-07-05 14:12:54,987 - WARNING - The file /path_analyses/test_velocyto/LNMA01.dedump.bam.pos.bam.name.bam already exists. The sorting step will be skipped and the existing file will be used.
2018-07-05 14:12:54,987 - WARNING - The file /path_analyses/test_velocyto/LNMA02.dedump.bam.pos.bam.name.bam already exists. The sorting step will be skipped and the existing file will be used.
2018-07-05 14:12:54,987 - INFO - Load the annotation from /path/Mus_musculus.GRCm38.90_UCSConlychr.gtf
2018-07-05 14:13:14,561 - DEBUG - Parsing Chromosome 1 strand - [line 0]
2018-07-05 14:13:18,025 - DEBUG - Done with 1- [line 58285]
2018-07-05 14:13:18,025 - DEBUG - Assigning indexes to genes
2018-07-05 14:13:18,074 - DEBUG - Seen 1695 genes until now

...

2018-07-05 14:14:20,632 - DEBUG - Parsing Chromosome 9 strand + [line 1609847]
2018-07-05 14:14:21,318 - DEBUG - Done with 9+ [line 1664785]
2018-07-05 14:14:21,319 - DEBUG - Assigning indexes to genes
2018-07-05 14:14:21,335 - DEBUG - Seen 48329 genes until now
2018-07-05 14:14:21,335 - DEBUG - Parsing Chromosome M strand - [line 1664786]
2018-07-05 14:14:21,335 - DEBUG - Done with M- [line 1664815]
2018-07-05 14:14:21,335 - DEBUG - Assigning indexes to genes
2018-07-05 14:14:21,335 - DEBUG - Seen 48338 genes until now
2018-07-05 14:14:21,336 - DEBUG - Parsing Chromosome M strand + [line 1664816]
2018-07-05 14:14:21,337 - DEBUG - Done with M+ [line 1664932]
2018-07-05 14:14:21,337 - DEBUG - Assigning indexes to genes
2018-07-05 14:14:21,337 - DEBUG - Seen 48366 genes until now
2018-07-05 14:14:21,337 - DEBUG - Parsing Chromosome X strand - [line 1664933]
2018-07-05 14:14:24,932 - DEBUG - Done with X- [line 1694755]
2018-07-05 14:14:24,933 - DEBUG - Assigning indexes to genes
2018-07-05 14:14:24,947 - DEBUG - Seen 49635 genes until now
2018-07-05 14:14:24,947 - DEBUG - Parsing Chromosome X strand + [line 1694756]
2018-07-05 14:14:25,575 - DEBUG - Done with X+ [line 1727994]
2018-07-05 14:14:25,576 - DEBUG - Assigning indexes to genes
2018-07-05 14:14:25,589 - DEBUG - Seen 50980 genes until now
2018-07-05 14:14:25,589 - DEBUG - Parsing Chromosome Y strand - [line 1727995]
2018-07-05 14:14:25,729 - DEBUG - Done with Y- [line 1734926]
2018-07-05 14:14:25,729 - DEBUG - Assigning indexes to genes
2018-07-05 14:14:25,736 - DEBUG - Seen 51860 genes until now
2018-07-05 14:14:25,736 - DEBUG - Parsing Chromosome Y strand + [line 1734927]
2018-07-05 14:14:25,868 - DEBUG - Assigning indexes to genes
2018-07-05 14:14:25,873 - DEBUG - Done with Y+ [line 1741516]
2018-07-05 14:14:25,874 - DEBUG - Fixing corner cases of transcript models containg intron longer than 1000Kbp
2018-07-05 14:14:31,470 - DEBUG - Generated 1433300 features corresponding to 131100 transcript models from /path/Mus_musculus.GRCm38.90_UCSConlychr.gtf
2018-07-05 14:14:31,507 - INFO - Scan /path_analyses/test_velocyto/LNMA01.dedump.bam.pos.bam.name.bam /path_analyses/test_velocyto/LNMA02.dedump.bam.pos.bam.name.bam to validate intron intervals
2018-07-05 14:14:49,986 - DEBUG - Reading /path_analyses/test_velocyto/LNMA01.dedump.bam.pos.bam.name.bam
2018-07-05 14:14:49,997 - DEBUG - Read first 0 million reads
2018-07-05 14:15:24,374 - DEBUG - End of file. Reset index: start scanning from initial position.
2018-07-05 14:15:24,375 - DEBUG - Reading /path_analyses/test_velocyto/LNMA02.dedump.bam.pos.bam.name.bam
2018-07-05 14:15:24,400 - DEBUG - Read first 0 million reads
2018-07-05 14:15:31,443 - DEBUG - End of file. Reset index: start scanning from initial position.
2018-07-05 14:15:31,443 - DEBUG - 912579 reads were skipped because no apropiate cell or umi barcode was found
2018-07-05 14:15:31,444 - DEBUG - Start molecule counting!
2018-07-05 14:15:37,984 - DEBUG - Features available for chromosomes : ['1-', '1+', '10-', '10+', '11-', '11+', '12-', '12+', '13-', '13+', '14-', '14+', '15-', '15+', '16-', '16+', '17-', '17+', '18-', '18+', '19-', '19+', '2-', '2+', '3-', '3+', '4-', '4+', '5-', '5+', '6-', '6+', '7-', '7+', '8-', '8+', '9-', '9+', 'M-', 'M+', 'X-', 'X+', 'Y-', 'Y+']
2018-07-05 14:15:37,985 - DEBUG - Mask available for chromosomes : []
2018-07-05 14:15:37,985 - DEBUG - Summarizing the results of intron validation.
2018-07-05 14:15:38,795 - DEBUG - Validated 0 introns (of which unique intervals 0) out of 651100 total possible introns (considering each possible transcript models).
2018-07-05 14:15:38,795 - DEBUG - Reading /path_analyses/test_velocyto/LNMA01.dedump.bam.pos.bam.name.bam
2018-07-05 14:15:38,798 - DEBUG - Read first 0 million reads
2018-07-05 14:15:55,566 - DEBUG - Counting for batch 1, containing 0 cells and 0 reads
2018-07-05 14:15:55,566 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2018-07-05 14:15:55,566 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
2018-07-05 14:15:55,567 - WARNING - 0 of the barcodes where without cell
2018-07-05 14:15:55,567 - DEBUG - Reading /path_analyses/test_velocyto/LNMA02.dedump.bam.pos.bam.name.bam
2018-07-05 14:15:55,570 - DEBUG - Read first 0 million reads
2018-07-05 14:16:04,264 - DEBUG - Counting for batch 2, containing 0 cells and 0 reads
2018-07-05 14:16:04,267 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2018-07-05 14:16:04,267 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
2018-07-05 14:16:04,268 - WARNING - 0 of the barcodes where without cell
2018-07-05 14:16:04,268 - DEBUG - 912579 reads were skipped because no apropiate cell or umi barcode was found
2018-07-05 14:16:04,268 - DEBUG - Counting done!
/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/matplotlib/font_manager.py:278: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '
Traceback (most recent call last):
  File "/path_analyses/software/miniconda/envs/velocyto/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto==0.17.8', 'console_scripts', 'velocyto')()
  File "/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/path_analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/_run.py", line 236, in _run
    logging.debug(f"Example of barcode: {valid_bcs_list[0]} and cell_id: {valid_cellid_list[0]}")
IndexError: list index out of range
```

Thank you in advance for your help

**Comment by gioelelm** [comment]
Thank you for the extra information.

The problem is somehow related with the content and format of the bam file as highlighted by the following lines in the log:

```
Counting for batch 1, containing 0 cells and 0 reads
Counting for batch 2, containing 0 cells and 0 reads
....
912579 reads were skipped because no appropriate cell or umi barcode was found
```

Can I ask which techniques is this? It looks like it might be SmartSeq2 (or any other technique that does not have UMIs).
If this is the case you should either use the `run_smartseq2` command or specify the option `without_umi`

Hope this helps. Let me know if this does not solve the issue and don't hesitate to get in contact again if you encounter other problems

**Comment by vagnec** [comment]
Hi,

I put the UMI in the XM flag. Here is how my bam files look:

```
K00201:191:HNVFNBBXX:1:1225:27600:17034_GTGAGTGA        272     chr1    3329451 1       48M12S  *       0       0     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCACTCACAGCACGGTTA     A<-FF<FAAA7-7--J<F-JFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA   NH:i:3  HI:i:3  NM:i:1  MD:Z:45G2       AS:i:45 nM:i:1  jM:B:c,-1       jI:B:i,-1       UG:i:0  XM:Z:GTGAGTGA
K00201:191:HNVFNBBXX:3:1215:10612:16155_TCTGGTTG        0       chr1    3736437 255     79M21S  *       0       0     TTCCACGAATCCAGCCCTTCAAAGGATAACACCAGAAAAAAAAAAATACAAGGACAGAAACCACGACCTAGAAAAAGCAGTGGTATCAACGCAGAGTACA     <<<-FF-FJ<J<JFJFJAAFJJJJJJJJJJJFFJJJFFFFJJJJJJFJJJF<JFJFJJFJJFFFJJJFJFJFJJJFAFJF7FJJJJJJJA7A<FJ<7FFF   NH:i:1  HI:i:1  NM:i:0  MD:Z:79AS:i:77 nM:i:0  jM:B:c,-1       jI:B:i,-1       UG:i:1  XM:Z:TCTGGTTG
K00201:191:HNVFNBBXX:3:2222:19441:34653_TCTGGTTG        0       chr1    3736437 255     79M21S  *       0       0     TTCCACGAATCCAGCCCTTCAAAGGATAACACCAGAAAAAAAAAAATACAAGGACAGAAACCACGACCTAGAAAAAGCAGTGGTATCAACGCAGAGTACA     A<77FF<JJJJFJJJFJFFFFJFFJJJJJJJJFJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJF7FJJFJJJJJJJAJFFFJFJJJJJJJJJJJJAAFFF   NH:i:1  HI:i:1  NM:i:0  MD:Z:79AS:i:77 nM:i:0  jM:B:c,-1       jI:B:i,-1       UG:i:1  XM:Z:TCTGGTTG
```
Unfortunately, UMIs are still not recognized....:

> 2018-07-25 09:59:17,265 - DEBUG - Reading /ifs/illumina/vagnec/Analyses/test_velocyto/bamfiles_test_XM/LNMA01_XM.pos.bam
> 2018-07-25 09:59:17,267 - DEBUG - Read first 0 million reads
> 2018-07-25 09:59:17,459 - DEBUG - Counting for batch 1, containing 0 cells and 0 reads
> 2018-07-25 09:59:17,459 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
> 2018-07-25 09:59:17,459 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
> 2018-07-25 09:59:17,460 - WARNING - 0 of the barcodes where without cell
> 2018-07-25 09:59:17,460 - DEBUG - Reading /ifs/illumina/vagnec/Analyses/test_velocyto/bamfiles_test_XM/LNMA02_XM.pos.bam
> 2018-07-25 09:59:17,461 - DEBUG - Read first 0 million reads
> 2018-07-25 09:59:17,465 - DEBUG - Counting for batch 2, containing 0 cells and 0 reads
> 2018-07-25 09:59:17,465 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
> 2018-07-25 09:59:17,466 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
> 2018-07-25 09:59:17,466 - WARNING - 0 of the barcodes where without cell
> 2018-07-25 09:59:17,466 - DEBUG - 13753 reads were skipped because no apropiate cell or umi barcode was found
> 2018-07-25 09:59:17,466 - DEBUG - Counting done!
> Traceback (most recent call last):
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/bin/velocyto", line 11, in <module>
>     load_entry_point('velocyto==0.17.8', 'console_scripts', 'velocyto')()
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
>     samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
>   File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/_run.py", line 236, in _run
>     logging.debug(f"Example of barcode: {valid_bcs_list[0]} and cell_id: {valid_cellid_list[0]}")
IndexError: list index out of range
> 
> 

I launched the same command with the option "--without-umi" and the job terminated sucessfully. So I really think the problem is with the recognition of UMIs.

Thank you in advance for your help

PS : my command:
`velocyto run --onefilepercell -o output2 bamfiles_test_XM/*XM.pos.bam /ifs/illumina/share/Utilities/Genomes/Mus_musculus/mm10/Annotations/Ensembl/Mus_musculus.GRCm38.90_UCSConlychr.gtf`

**Comment by gioelelm** [comment]
I think you stumbled upon an actual bug.
I fixed it in 0.17.9, however, I had some problems to upload it on pypi, I will solve within 24h, but for now, you will have to install from source.

**Comment by gioelelm** [comment]
Please close the issue if the bug is solved, otherwise let me know

**Comment by vagnec** [comment]
Hi gioelelm,
Yes, it worked with the new version. Thank you !

**Comment by annajbott** [comment]
> Hi,
> 
> I put the UMI in the XM flag. Here is how my bam files look:
> 
> ```
> K00201:191:HNVFNBBXX:1:1225:27600:17034_GTGAGTGA        272     chr1    3329451 1       48M12S  *       0       0     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCACTCACAGCACGGTTA     A<-FF<FAAA7-7--J<F-JFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA   NH:i:3  HI:i:3  NM:i:1  MD:Z:45G2       AS:i:45 nM:i:1  jM:B:c,-1       jI:B:i,-1       UG:i:0  XM:Z:GTGAGTGA
> K00201:191:HNVFNBBXX:3:1215:10612:16155_TCTGGTTG        0       chr1    3736437 255     79M21S  *       0       0     TTCCACGAATCCAGCCCTTCAAAGGATAACACCAGAAAAAAAAAAATACAAGGACAGAAACCACGACCTAGAAAAAGCAGTGGTATCAACGCAGAGTACA     <<<-FF-FJ<J<JFJFJAAFJJJJJJJJJJJFFJJJFFFFJJJJJJFJJJF<JFJFJJFJJFFFJJJFJFJFJJJFAFJF7FJJJJJJJA7A<FJ<7FFF   NH:i:1  HI:i:1  NM:i:0  MD:Z:79AS:i:77 nM:i:0  jM:B:c,-1       jI:B:i,-1       UG:i:1  XM:Z:TCTGGTTG
> K00201:191:HNVFNBBXX:3:2222:19441:34653_TCTGGTTG        0       chr1    3736437 255     79M21S  *       0       0     TTCCACGAATCCAGCCCTTCAAAGGATAACACCAGAAAAAAAAAAATACAAGGACAGAAACCACGACCTAGAAAAAGCAGTGGTATCAACGCAGAGTACA     A<77FF<JJJJFJJJFJFFFFJFFJJJJJJJJFJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJF7FJJFJJJJJJJAJFFFJFJJJJJJJJJJJJAAFFF   NH:i:1  HI:i:1  NM:i:0  MD:Z:79AS:i:77 nM:i:0  jM:B:c,-1       jI:B:i,-1       UG:i:1  XM:Z:TCTGGTTG
> ```
> Unfortunately, UMIs are still not recognized....:
> 
> > 2018-07-25 09:59:17,265 - DEBUG - Reading /ifs/illumina/vagnec/Analyses/test_velocyto/bamfiles_test_XM/LNMA01_XM.pos.bam
> > 2018-07-25 09:59:17,267 - DEBUG - Read first 0 million reads
> > 2018-07-25 09:59:17,459 - DEBUG - Counting for batch 1, containing 0 cells and 0 reads
> > 2018-07-25 09:59:17,459 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
> > 2018-07-25 09:59:17,459 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
> > 2018-07-25 09:59:17,460 - WARNING - 0 of the barcodes where without cell
> > 2018-07-25 09:59:17,460 - DEBUG - Reading /ifs/illumina/vagnec/Analyses/test_velocyto/bamfiles_test_XM/LNMA02_XM.pos.bam
> > 2018-07-25 09:59:17,461 - DEBUG - Read first 0 million reads
> > 2018-07-25 09:59:17,465 - DEBUG - Counting for batch 2, containing 0 cells and 0 reads
> > 2018-07-25 09:59:17,465 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
> > 2018-07-25 09:59:17,466 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
> > 2018-07-25 09:59:17,466 - WARNING - 0 of the barcodes where without cell
> > 2018-07-25 09:59:17,466 - DEBUG - 13753 reads were skipped because no apropiate cell or umi barcode was found
> > 2018-07-25 09:59:17,466 - DEBUG - Counting done!
> > Traceback (most recent call last):
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/bin/velocyto", line 11, in 
> > load_entry_point('velocyto==0.17.8', 'console_scripts', 'velocyto')()
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 722, in **call**
> > return self.main(*args, **kwargs)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 697, in main
> > rv = self.invoke(ctx)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
> > return _process_result(sub_ctx.command.invoke(sub_ctx))
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 895, in invoke
> > return ctx.invoke(self.callback, **ctx.params)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 535, in invoke
> > return callback(*args, **kwargs)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
> > samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/_run.py", line 236, in _run
> > logging.debug(f"Example of barcode: {valid_bcs_list[0]} and cell_id: {valid_cellid_list[0]}")
> > IndexError: list index out of range
> 
> I launched the same command with the option "--without-umi" and the job terminated sucessfully. So I really think the problem is with the recognition of UMIs.
> 
> Thank you in advance for your help
> 
> PS : my command:
> `velocyto run --onefilepercell -o output2 bamfiles_test_XM/*XM.pos.bam /ifs/illumina/share/Utilities/Genomes/Mus_musculus/mm10/Annotations/Ensembl/Mus_musculus.GRCm38.90_UCSConlychr.gtf`



> Hi,
> 
> I put the UMI in the XM flag. Here is how my bam files look:
> 
> ```
> K00201:191:HNVFNBBXX:1:1225:27600:17034_GTGAGTGA        272     chr1    3329451 1       48M12S  *       0       0     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCACTCACAGCACGGTTA     A<-FF<FAAA7-7--J<F-JFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA   NH:i:3  HI:i:3  NM:i:1  MD:Z:45G2       AS:i:45 nM:i:1  jM:B:c,-1       jI:B:i,-1       UG:i:0  XM:Z:GTGAGTGA
> K00201:191:HNVFNBBXX:3:1215:10612:16155_TCTGGTTG        0       chr1    3736437 255     79M21S  *       0       0     TTCCACGAATCCAGCCCTTCAAAGGATAACACCAGAAAAAAAAAAATACAAGGACAGAAACCACGACCTAGAAAAAGCAGTGGTATCAACGCAGAGTACA     <<<-FF-FJ<J<JFJFJAAFJJJJJJJJJJJFFJJJFFFFJJJJJJFJJJF<JFJFJJFJJFFFJJJFJFJFJJJFAFJF7FJJJJJJJA7A<FJ<7FFF   NH:i:1  HI:i:1  NM:i:0  MD:Z:79AS:i:77 nM:i:0  jM:B:c,-1       jI:B:i,-1       UG:i:1  XM:Z:TCTGGTTG
> K00201:191:HNVFNBBXX:3:2222:19441:34653_TCTGGTTG        0       chr1    3736437 255     79M21S  *       0       0     TTCCACGAATCCAGCCCTTCAAAGGATAACACCAGAAAAAAAAAAATACAAGGACAGAAACCACGACCTAGAAAAAGCAGTGGTATCAACGCAGAGTACA     A<77FF<JJJJFJJJFJFFFFJFFJJJJJJJJFJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJF7FJJFJJJJJJJAJFFFJFJJJJJJJJJJJJAAFFF   NH:i:1  HI:i:1  NM:i:0  MD:Z:79AS:i:77 nM:i:0  jM:B:c,-1       jI:B:i,-1       UG:i:1  XM:Z:TCTGGTTG
> ```
> Unfortunately, UMIs are still not recognized....:
> 
> > 2018-07-25 09:59:17,265 - DEBUG - Reading /ifs/illumina/vagnec/Analyses/test_velocyto/bamfiles_test_XM/LNMA01_XM.pos.bam
> > 2018-07-25 09:59:17,267 - DEBUG - Read first 0 million reads
> > 2018-07-25 09:59:17,459 - DEBUG - Counting for batch 1, containing 0 cells and 0 reads
> > 2018-07-25 09:59:17,459 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
> > 2018-07-25 09:59:17,459 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
> > 2018-07-25 09:59:17,460 - WARNING - 0 of the barcodes where without cell
> > 2018-07-25 09:59:17,460 - DEBUG - Reading /ifs/illumina/vagnec/Analyses/test_velocyto/bamfiles_test_XM/LNMA02_XM.pos.bam
> > 2018-07-25 09:59:17,461 - DEBUG - Read first 0 million reads
> > 2018-07-25 09:59:17,465 - DEBUG - Counting for batch 2, containing 0 cells and 0 reads
> > 2018-07-25 09:59:17,465 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
> > 2018-07-25 09:59:17,466 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
> > 2018-07-25 09:59:17,466 - WARNING - 0 of the barcodes where without cell
> > 2018-07-25 09:59:17,466 - DEBUG - 13753 reads were skipped because no apropiate cell or umi barcode was found
> > 2018-07-25 09:59:17,466 - DEBUG - Counting done!
> > Traceback (most recent call last):
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/bin/velocyto", line 11, in 
> > load_entry_point('velocyto==0.17.8', 'console_scripts', 'velocyto')()
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 722, in **call**
> > return self.main(*args, **kwargs)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 697, in main
> > rv = self.invoke(ctx)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
> > return _process_result(sub_ctx.command.invoke(sub_ctx))
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 895, in invoke
> > return ctx.invoke(self.callback, **ctx.params)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 535, in invoke
> > return callback(*args, **kwargs)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
> > samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
> > File "/ifs/illumina/vagnec/Analyses/software/miniconda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/_run.py", line 236, in _run
> > logging.debug(f"Example of barcode: {valid_bcs_list[0]} and cell_id: {valid_cellid_list[0]}")
> > IndexError: list index out of range
> 
> I launched the same command with the option "--without-umi" and the job terminated sucessfully. So I really think the problem is with the recognition of UMIs.
> 
> Thank you in advance for your help
> 
> PS : my command:
> `velocyto run --onefilepercell -o output2 bamfiles_test_XM/*XM.pos.bam /ifs/illumina/share/Utilities/Genomes/Mus_musculus/mm10/Annotations/Ensembl/Mus_musculus.GRCm38.90_UCSConlychr.gtf`

Hi,
I am using UMI tools (/Alevin with no quant output) and have the UMIs and CBs located in the name of the read too and need them as tags for velocyto. Did you use a tool to add the barcodes as tags? I've been reading a lot of documentation but can't seem to find anything that will do this efficiently (I might not have been looking very well though haha). I'm looking for an approach that is generalisable and not too slow. Thanks! 

Anna

**Comment by massonix** [comment]
Hi,

I'm getting exactly the same error but with 10X data

**Comment by Genki-YAN** [comment]
> Hi,
> 
> I'm getting exactly the same error but with 10X data

Hi,
I have the same error with 10X data too.
Have you solved the problem yet?
Can you give me some advice?

**Comment by sunnymiraekim** [comment]
Hi,
I'm getting the same error with smartseq2. 
Does anyone have any advice?
