### ISSUE TITLE
Segmentation fault (core dumped) when start velocyto

### ISSUE THREAD

**Issue by wulabupenn** [velocyto-team/velocyto.py#98]
Hi,

I received the following error message when I type `velocyto --help`
![image](https://user-images.githubusercontent.com/33881425/44375308-f1128900-a4c0-11e8-8c3f-0fbe2475e5c4.png)

I checked the issue #53 then I modify the setup.py file, but I got another error message in below:
**Segmentation fault (core dumped)**

**Comment by gioelelm** [comment]
This is a compiler error. First time I see this. I don't know how to solve
it. Maybe start a conda environment from scratch and try the installation
again?

**Comment by wulabupenn** [comment]
Thank you for the prompt reply. I will have a try from scratch.

**Comment by galib36** [comment]
Hi,
When I run velocyto --help, I see Segmentation fault (core dumped) error. How can I solve the problem?

**Comment by galib36** [comment]
Hello gioelelm,
I have solved the issue, needed to install gcc-5 with the command `conda install -c psi4 gcc-5` and then `conda install -c anaconda libgcc`

**Comment by gioelelm** [comment]
Great!

**Comment by galib36** [comment]
Hello gioelelm,
After I updated my conda I am again getting the `Segmentation fault (core dumped)` error. The solution that I used previously is not working now. Can you please suggest me how to fix it.
