### ISSUE TITLE
reporting "UMI missing" with '-U' has already been set

### ISSUE THREAD

**Issue by QidiFeng** [velocyto-team/velocyto.py#99]
Dear Velocyto Team,

I tried to use velocity.py to deal with Fluidigm C1 alignment bam file, and the command is 'velocyto run -U -o test SRR1275387.transcript.bam Homo_sapiens.GRCh38.83.gtf'. However, it is reporting error:
"OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag."

Besides, 'run smartseq2' would also report the same error.

Would you please me to figure out what is going on? Thank you very much!

Sincerely, 
Qidi

**Comment by gioelelm** [comment]
Have you considered the first message?Could it be that the bam file is not
correctly formatted? Could you run 'samtools view BAMFILE | head' and share
the results?

**Comment by leezx** [comment]
I have the same problem as QidiFeng.

my date was from smart-seq platform, each bam file was a cell. so, there were no UMIs.

I have sorted the bam file according to the positions.

Here's my command:
velocyto run_smartseq2 -o OUTPUT -m GRCh38_rmsk.gtf -e 10c2-E11-P21  10c2-E11-P21Aligned.outsort.bam Homo_sapiens.GRCh38.91.gtf

Here's the error:
OSError: The bam file does not contain umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.

I have checked the bugs. it seems "velocyto/counter.py" didn't work well.

below is the python function:
def peek(self, bamfile: str, lines: int=1000) -> None:
        """Peeks into the samfile to determine if it is a cellranger or dropseq file
        """
        logging.debug(f"Peeking into {bamfile}")
        fin = pysam.AlignmentFile(bamfile)  # type: pysam.AlignmentFile
        cellranger: int = 0
        dropseq: int = 0
        failed: int = 0
        for i, read in enumerate(fin):
            if read.is_unmapped:
                continue
            if read.has_tag("CB") and read.has_tag("UB"):
                cellranger += 1
            elif read.has_tag("XC") and read.has_tag("XM"):
                dropseq += 1
            else:
                logging.warn(f"Not found cell and umi barcode in entry {i} of the bam file")
                failed += 1
            if cellranger > lines:
                self.cellbarcode_str = "CB"
                self.umibarcode_str = "UB"
                break
            elif dropseq > lines:
                self.cellbarcode_str = "XC"
                self.umibarcode_str = "XM"
                break
            elif failed > 5 * lines:
                raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
            else:
                pass
        fin.close()

there were no "CB", "UB", "XC" and "XM" tags in my bam file. so it will always get this error.

can I directly annotate this line? 
raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
can you develop a version for smart-seq?
the situation is I just have the bam file, each bam file is a cell, there's no tag in my bam file. Thanks.

BTW, below is part of the bam file:
C00135:275:CCHA0ANXX:1:2208:6180:35303  99      1       14414   255     101M    =       185259  171085  GTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCACAGGCTGGGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGA   <BBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   NH:i:1  HI:i:1  AS:i:197        nM:i:1
C00135:275:CCHA0ANXX:1:1104:11846:95456 99      1       14460   0       101M    =       186372  172011  ACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCGCCCCAGCTGTGTGGCCTCAAGCCAGCCTTCCGCTCCTT   BBBBBBFB<FFFFFFFFFBFFFFFFFFFFFFFFFBFFFFFFBFFFFFFFBF<BFBFFBF<FBFFFFFFFF7FBFFFFFFFF/BFFFFFFFBFFFFFFBFFF   NH:i:5  HI:i:1  AS:i:196        nM:i:0

**Comment by gioelelm** [comment]
Which version are you running?

**Comment by leezx** [comment]
the latest one 0.17. thanks
```
velocyto, version 0.17.10
```

**Comment by gioelelm** [comment]
I tried a patch. Could you try installing from source and check if the bug is fixed?
If it is fixed I will release it as 0.17.11

**Comment by leezx** [comment]
wow, so quick...
I have reinstalled it and the loom file was generated successfully!
Thanks a lot!

**Comment by gioelelm** [comment]
The generation of the file was maybe too quick... checked that there is data inside?

**Comment by leezx** [comment]
I just tested the tool on one cell, so it was quite quick.
Here's the result in the loom file. 

```python
>>> vlm.S_norm.shape
(58302, 1)
>>> numpy.percentile(vlm.S_norm, numpy.arange(1,100,5))
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 2.32192809, 7.01122726])
```

it seems ~90% of the values were 0. was it normal?

**Comment by gioelelm** [comment]
Yes I would say so. How many reads per cell. How many non-zero genes?

**Comment by leezx** [comment]
it's about 1-2 million reads per cell and the detected gene number is about 3000~9000 (median: ~5000).

**Comment by gioelelm** [comment]
Ok, it worked. I am releasing 0.17.11 in few minutes will be available thorugh `pip`

**Comment by leezx** [comment]
ok, thanks so much!

**Comment by gioelelm** [comment]
I close. @QidiFeng if this did not solve it for you feel free to reopen.

**Comment by leeyoyohku** [comment]
Hi @gioelelm !

I seem to be running into this issue again. I encountered the following error as I typed `velocyto run -U -o 2_velocyto/ 1_STAR/pEPSC_1Aligned.sortedByCoord.out.bam /home/yoyo/yoyo/0_reference/sus_scr11/GCF_000003025.6_Sscrofa11.1_genomic.gtf` in command. 

`Traceback (most recent call last):
  File "/home/yoyo/miniconda2/envs/notebook/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/velocyto/commands/_run.py", line 159, in _run
    exincounter.peek(bamfile[0])
  File "/home/yoyo/miniconda2/envs/notebook/lib/python3.6/site-packages/velocyto/counter.py", line 158, in peek
    raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.`

I also cross-checked the bam file and you can see the bam as in the capture.

Appreciate it if you can offer help resolving the error. Thanks!!
<img width="2374" alt="WeChat214c6967fb787a89e1f0f535327412b8" src="https://user-images.githubusercontent.com/52441289/100320880-ce0aa400-2ffc-11eb-884b-818ab7fb567a.png">
